/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/allosteric/.choosenim/toolchains/nim-0.18.0/lib -o /media/allosteric/Data/Arts/nim/BeforeGamer/Push/src/nimcache/push.o /media/allosteric/Data/Arts/nim/BeforeGamer/Push/src/nimcache/push.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_BoxcolonObjectType__CcD6IYPdn4nlPMYfEQhewQ tyObject_BoxcolonObjectType__CcD6IYPdn4nlPMYfEQhewQ;
typedef struct tyTuple_DTy5no9cl66GOLoMhrMJm8A tyTuple_DTy5no9cl66GOLoMhrMJm8A;
typedef struct tyObject_Table_nIG4O9c9a3gnDGm0H0nP9aqvA tyObject_Table_nIG4O9c9a3gnDGm0H0nP9aqvA;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tySequence_y9aTBJ79cxanGa2fAuei6iIg tySequence_y9aTBJ79cxanGa2fAuei6iIg;
typedef struct tyTuple_Yt1nTvhqbfseJu4tLVyjRw tyTuple_Yt1nTvhqbfseJu4tLVyjRw;
typedef struct tyObject_Map_bwPsPqooz39aY9cFequ9cPMZg tyObject_Map_bwPsPqooz39aY9cFequ9cPMZg;
typedef struct tyObject_PlayercolonObjectType__YKSlBm59bz8cnvLRFi6TueA tyObject_PlayercolonObjectType__YKSlBm59bz8cnvLRFi6TueA;
typedef struct tyObject_BoxTargetcolonObjectType__RZuy9cwz9cfw8y9ab8un3pUpQ tyObject_BoxTargetcolonObjectType__RZuy9cwz9cfw8y9ab8un3pUpQ;
typedef struct tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tySequence_uB9b75OUPRENsBAu4AnoePA tySequence_uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyTuple_qmFwV9bFQ9a4cxfYwLzDR0lQ tyTuple_qmFwV9bFQ9a4cxfYwLzDR0lQ;
typedef struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
struct tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ {
NI Field0;
NI Field1;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_BoxcolonObjectType__CcD6IYPdn4nlPMYfEQhewQ {
tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ pos;
};
typedef NU8 tyEnum_InputAction_65PXn9bhXPOUlLz1qL3PCeQ;
typedef NimStringDesc* tyArray_Re75IspeoxXy2oCZHwcRrA[2];
typedef NU8 tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw;
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_Table_nIG4O9c9a3gnDGm0H0nP9aqvA {
tySequence_y9aTBJ79cxanGa2fAuei6iIg* data;
NI counter;
};
struct tyTuple_Yt1nTvhqbfseJu4tLVyjRw {
NI Field0;
tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw Field1;
tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ Field2;
};
typedef tyObject_BoxcolonObjectType__CcD6IYPdn4nlPMYfEQhewQ* tyArray_O1t8Odh9cUegkP1sczBQjlA[2];
typedef tyObject_BoxTargetcolonObjectType__RZuy9cwz9cfw8y9ab8un3pUpQ* tyArray_PWHgkvTkJgyby9afHn9a1osw[2];
struct tyObject_Map_bwPsPqooz39aY9cFequ9cPMZg {
tyObject_PlayercolonObjectType__YKSlBm59bz8cnvLRFi6TueA* player;
tyArray_O1t8Odh9cUegkP1sczBQjlA boxes;
tyArray_PWHgkvTkJgyby9afHn9a1osw boxTargets;
};
struct tyObject_PlayercolonObjectType__YKSlBm59bz8cnvLRFi6TueA {
tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ pos;
};
struct tyObject_BoxTargetcolonObjectType__RZuy9cwz9cfw8y9ab8un3pUpQ {
tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ pos;
};
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
struct tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA {
  Exception Sup;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
typedef NIM_CHAR tyArray_9bPFPkkEEeeNM9bKgiV8Q49cg[6];
typedef tyArray_9bPFPkkEEeeNM9bKgiV8Q49cg tyArray_9addaGct6lvVwXAeOuCK73g[3];
typedef NU8 tyEnum_DestinStatus_uWnJ20JvX6gkNBB7pR6M6w;
struct tyTuple_qmFwV9bFQ9a4cxfYwLzDR0lQ {
tyEnum_DestinStatus_uWnJ20JvX6gkNBB7pR6M6w Field0;
NI Field1;
};
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc_RqErSzKvAG3vZYqc85mVBA) (NI value, NI size);
struct tyTuple_DTy5no9cl66GOLoMhrMJm8A {
tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw Field0;
tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ Field1;
};
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_y9aTBJ79cxanGa2fAuei6iIg {
  TGenericSeq Sup;
  tyTuple_Yt1nTvhqbfseJu4tLVyjRw data[SEQ_DECL_SIZE];
};
struct tySequence_uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ, nthCoord_YnKvJistBbyRII7Pq9ajnIA)(NI n, NI width, NI height);
static N_INLINE(NI, modInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ, plus__V69cd9cWTLH4esNl9b6zfgteA)(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ pos0, tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ pos1);
static N_INLINE(NI, addInt)(NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__mr9aVLAUz5GU2Vb6MCHzy5g)(tyObject_BoxcolonObjectType__CcD6IYPdn4nlPMYfEQhewQ* box);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__76rXyWcsgGy3rg1rEcHNNw)(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ x);
N_LIB_PRIVATE N_NIMCALL(tyEnum_InputAction_65PXn9bhXPOUlLz1qL3PCeQ, getInput_RfMgKTO9bx69b9bT3oeCLrvwA)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, readLine_fPRnXwDTqtynUYGl4OixAg)(FILE* f);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size);
N_LIB_PRIVATE N_NIMCALL(void, toTable_9aiFeC7cDng115aPs81eeFQ)(tyTuple_DTy5no9cl66GOLoMhrMJm8A* pairs, NI pairsLen_0, tyObject_Table_nIG4O9c9a3gnDGm0H0nP9aqvA* Result);
N_LIB_PRIVATE N_NIMCALL(void, initTable_N7bjLk6dihuKs0wAHJ9cAaQ)(NI initialSize, tyObject_Table_nIG4O9c9a3gnDGm0H0nP9aqvA* Result);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq__mGV0T7Bw850xV3ze03Q9cJw)(tyObject_Table_nIG4O9c9a3gnDGm0H0nP9aqvA* t, tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw key, tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ val);
static N_INLINE(NI, rawGet_AHdLKezz07NuzDUvZosDZgtables)(tyObject_Table_nIG4O9c9a3gnDGm0H0nP9aqvA t, tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw key, NI* hc);
static N_INLINE(NI, hash_wja033thh0Z4NAd9bdBGScwtables)(tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw x);
static N_INLINE(NIM_BOOL, isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables)(NI hcode);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, nextTry_OLPhxSyW9bte5CwHzzQVhfAtables)(NI h, NI maxHash);
static N_INLINE(NI, subInt)(NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(void, enlarge_aOo9ajIlXKCyMmB9ajxWw9a4g)(tyObject_Table_nIG4O9c9a3gnDGm0H0nP9aqvA* t);
N_LIB_PRIVATE N_NIMCALL(void, rawInsert_JIx5ModQQZZoBfiSfMt3gQ)(tyObject_Table_nIG4O9c9a3gnDGm0H0nP9aqvA* t, tySequence_y9aTBJ79cxanGa2fAuei6iIg** data, tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw key, tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ val, NI hc, NI h);
static N_INLINE(NI, rawGetKnownHC_n60yivyEBqJdPM2o7lYUhQtables)(tyObject_Table_nIG4O9c9a3gnDGm0H0nP9aqvA t, tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw key, NI hc);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted_nyaZAljVI03SH2d9cnD0WMw)(NimStringDesc** s, NI x);
static N_NIMCALL(void, Marker_tyRef_pF0A5b9a9bWqyJfPW89cModmA)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef_5m1ohdzyS0OmNkC7RPxo9bQ)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef_LtDmL6a1ws79cyGkTS4ZDOQ)(void* p, NI op);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_LIB_PRIVATE N_NIMCALL(tyObject_PlayercolonObjectType__YKSlBm59bz8cnvLRFi6TueA*, new_Z9bPY53FJdVBzfJKSz2bGgA)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_BoxcolonObjectType__CcD6IYPdn4nlPMYfEQhewQ*, new_vJa1Px3VC82L38Sg03Basg)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_BoxTargetcolonObjectType__RZuy9cwz9cfw8y9ab8un3pUpQ*, new_pGC2AQ3Hz7ppk6U7Vccb3w)(void);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(void, genericAssign)(void* dest, void* src, TNimType* mt);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getVisualMap_RhT0OpkXSHhOHnnNAmrMfA)(tyObject_Map_bwPsPqooz39aY9cFequ9cPMZg* map);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuRepeatChar)(NIM_CHAR c, NI count);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, join_nTMIi7o8Zy13sFPeiBsCQA)(NIM_CHAR* a, NI aLen_0, NimStringDesc* sep);
N_LIB_PRIVATE N_NIMCALL(NI, getIBoxAt_HWq9axnMLwPIY9bd6Ojr39bhA)(tyObject_Map_bwPsPqooz39aY9cFequ9cPMZg* map, tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ pos);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, eqeq__GMdYAiXVYFtXgUAy83DYgg)(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ x, tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ y);
N_LIB_PRIVATE N_NIMCALL(void, movePlayer_hHlfeVjp62CR2MvBikJH2g)(tyObject_Map_bwPsPqooz39aY9cFequ9cPMZg* map, tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw direct);
N_LIB_PRIVATE N_NIMCALL(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ, X5BX5D__M8fLPtDcT9aAoQyfTfVp6TA)(tyObject_Table_nIG4O9c9a3gnDGm0H0nP9aqvA t, tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw key);
N_LIB_PRIVATE N_NIMCALL(tyTuple_qmFwV9bFQ9a4cxfYwLzDR0lQ, getDestinStatus_U3MREanvOWwZ9a3ts14lQtA)(tyObject_Map_bwPsPqooz39aY9cFequ9cPMZg* map, tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ destin);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, colonanonymous__8llUUXRaS7N2Rhect6F0PQ)(NI value, NI size);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
TNimType NTI_cLjoWhgzLRaR7YLGawE7Uw_;
TNimType NTI_1v9bKyksXWMsm0vNwmZ4EuQ_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
TNimType NTI_bwPsPqooz39aY9cFequ9cPMZg_;
TNimType NTI_YKSlBm59bz8cnvLRFi6TueA_;
TNimType NTI_pF0A5b9a9bWqyJfPW89cModmA_;
TNimType NTI_CcD6IYPdn4nlPMYfEQhewQ_;
TNimType NTI_5m1ohdzyS0OmNkC7RPxo9bQ_;
TNimType NTI_O1t8Odh9cUegkP1sczBQjlA_;
TNimType NTI_RZuy9cwz9cfw8y9ab8un3pUpQ_;
TNimType NTI_LtDmL6a1ws79cyGkTS4ZDOQ_;
TNimType NTI_PWHgkvTkJgyby9afHn9a1osw_;
extern TNimType NTI_yCEN9anxCD6mzBxGjuaRBdg_;
extern TNimType NTI_Gi06FkNeykJn7mrqRZYrkA_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
STRING_LITERAL(TM_3idqVVpbLQLcl3rcp2D9asw_6, "input is ", 9);
STRING_LITERAL(TM_3idqVVpbLQLcl3rcp2D9asw_7, "w", 1);
STRING_LITERAL(TM_3idqVVpbLQLcl3rcp2D9asw_8, "s", 1);
STRING_LITERAL(TM_3idqVVpbLQLcl3rcp2D9asw_9, "a", 1);
STRING_LITERAL(TM_3idqVVpbLQLcl3rcp2D9asw_10, "d", 1);
STRING_LITERAL(TM_3idqVVpbLQLcl3rcp2D9asw_11, "q", 1);
STRING_LITERAL(TM_3idqVVpbLQLcl3rcp2D9asw_20, "Map is too small", 16);
STRING_LITERAL(TM_3idqVVpbLQLcl3rcp2D9asw_28, "", 0);
STRING_LITERAL(TM_3idqVVpbLQLcl3rcp2D9asw_29, "\012", 1);
STRING_LITERAL(TM_3idqVVpbLQLcl3rcp2D9asw_30, "#", 1);
STRING_LITERAL(TM_3idqVVpbLQLcl3rcp2D9asw_31, "#\012", 2);
NIM_CONST struct {
  TGenericSeq Sup;
  tyTuple_Yt1nTvhqbfseJu4tLVyjRw data[16];
} TM_3idqVVpbLQLcl3rcp2D9asw_36 = {{16, 16}, {{((NI) 0),
((tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw) 0),
{((NI) 0),
((NI) 0)}
}
,
{((NI) 314159265),
((tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw) 0),
{((NI) 0),
((NI) -1)}
}
,
{((NI) 1),
((tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw) 1),
{((NI) 0),
((NI) 1)}
}
,
{((NI) 2),
((tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw) 2),
{((NI) -1),
((NI) 0)}
}
,
{((NI) 3),
((tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw) 3),
{((NI) 1),
((NI) 0)}
}
,
{((NI) 4),
((tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw) 4),
{((NI) 0),
((NI) 0)}
}
,
{((NI) 0),
((tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw) 0),
{((NI) 0),
((NI) 0)}
}
,
{((NI) 0),
((tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw) 0),
{((NI) 0),
((NI) 0)}
}
,
{((NI) 0),
((tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw) 0),
{((NI) 0),
((NI) 0)}
}
,
{((NI) 0),
((tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw) 0),
{((NI) 0),
((NI) 0)}
}
,
{((NI) 0),
((tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw) 0),
{((NI) 0),
((NI) 0)}
}
,
{((NI) 0),
((tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw) 0),
{((NI) 0),
((NI) 0)}
}
,
{((NI) 0),
((tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw) 0),
{((NI) 0),
((NI) 0)}
}
,
{((NI) 0),
((tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw) 0),
{((NI) 0),
((NI) 0)}
}
,
{((NI) 0),
((tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw) 0),
{((NI) 0),
((NI) 0)}
}
,
{((NI) 0),
((tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw) 0),
{((NI) 0),
((NI) 0)}
}
}};
NIM_CONST tyObject_Table_nIG4O9c9a3gnDGm0H0nP9aqvA TM_3idqVVpbLQLcl3rcp2D9asw_35 = {((tySequence_y9aTBJ79cxanGa2fAuei6iIg*)&TM_3idqVVpbLQLcl3rcp2D9asw_36), ((NI) 5)};
NIM_CONST tyTuple_qmFwV9bFQ9a4cxfYwLzDR0lQ TM_3idqVVpbLQLcl3rcp2D9asw_37 = {((tyEnum_DestinStatus_uWnJ20JvX6gkNBB7pR6M6w) 1),
((NI) -1)}
;
NIM_CONST tyTuple_qmFwV9bFQ9a4cxfYwLzDR0lQ TM_3idqVVpbLQLcl3rcp2D9asw_38 = {((tyEnum_DestinStatus_uWnJ20JvX6gkNBB7pR6M6w) 0),
((NI) -1)}
;

static N_INLINE(NI, modInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		if (!(b == ((NI) 0))) goto LA3_;
		raiseDivByZero();
	}
	LA3_: ;
	result = (NI)(a % b);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		if (!(b == ((NI) 0))) goto LA3_;
		raiseDivByZero();
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == ((NI) (IL64(-9223372036854775807) - IL64(1))));
		if (!(T7_)) goto LA8_;
		T7_ = (b == ((NI) -1));
		LA8_: ;
		if (!T7_) goto LA9_;
		raiseOverflow();
	}
	LA9_: ;
	result = (NI)(a / b);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ, nthCoord_YnKvJistBbyRII7Pq9ajnIA)(NI n, NI width, NI height) {
	tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ result;
	NI TM_3idqVVpbLQLcl3rcp2D9asw_2;
	NI TM_3idqVVpbLQLcl3rcp2D9asw_3;
	nimfr_("nthCoord", "push.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(43, "push.nim");
	TM_3idqVVpbLQLcl3rcp2D9asw_2 = modInt(n, width);
	result.Field0 = (NI)(TM_3idqVVpbLQLcl3rcp2D9asw_2);
	nimln_(44, "push.nim");
	TM_3idqVVpbLQLcl3rcp2D9asw_3 = divInt(n, width);
	result.Field1 = (NI)(TM_3idqVVpbLQLcl3rcp2D9asw_3);
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ, plus__V69cd9cWTLH4esNl9b6zfgteA)(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ pos0, tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ pos1) {
	tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ result;
	NI TM_3idqVVpbLQLcl3rcp2D9asw_4;
	NI TM_3idqVVpbLQLcl3rcp2D9asw_5;
	nimfr_("+", "push.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(48, "push.nim");
	TM_3idqVVpbLQLcl3rcp2D9asw_4 = addInt(pos0.Field0, pos1.Field0);
	result.Field0 = (NI)(TM_3idqVVpbLQLcl3rcp2D9asw_4);
	TM_3idqVVpbLQLcl3rcp2D9asw_5 = addInt(pos0.Field1, pos1.Field1);
	result.Field1 = (NI)(TM_3idqVVpbLQLcl3rcp2D9asw_5);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__mr9aVLAUz5GU2Vb6MCHzy5g)(tyObject_BoxcolonObjectType__CcD6IYPdn4nlPMYfEQhewQ* box) {
	NimStringDesc* result;
	nimfr_("$", "push.nim");
	result = (NimStringDesc*)0;
	nimln_(50, "push.nim");
	result = dollar__76rXyWcsgGy3rg1rEcHNNw((*box).pos);
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = memcmp(a, b, ((size_t) (size)));
	result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL T11_;
{	result = (NIM_BOOL)0;
	{
		if (!(a == b)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == NIM_NIL);
		if (T7_) goto LA8_;
		T7_ = (b == NIM_NIL);
		LA8_: ;
		if (!T7_) goto LA9_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA9_: ;
	T11_ = (NIM_BOOL)0;
	T11_ = ((*a).Sup.len == (*b).Sup.len);
	if (!(T11_)) goto LA12_;
	T11_ = equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem(((void*) ((*a).data)), ((void*) ((*b).data)), ((NI) ((*a).Sup.len)));
	LA12_: ;
	result = T11_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyEnum_InputAction_65PXn9bhXPOUlLz1qL3PCeQ, getInput_RfMgKTO9bx69b9bT3oeCLrvwA)(void) {
	tyEnum_InputAction_65PXn9bhXPOUlLz1qL3PCeQ result;
	NimStringDesc* input;
	tyArray_Re75IspeoxXy2oCZHwcRrA T1_;
	nimfr_("getInput", "push.nim");
	result = (tyEnum_InputAction_65PXn9bhXPOUlLz1qL3PCeQ)0;
	nimln_(161, "push.nim");
	input = readLine_fPRnXwDTqtynUYGl4OixAg(stdin);
	nimln_(162, "push.nim");
	memset((void*)T1_, 0, sizeof(T1_));
	T1_[0] = copyString(((NimStringDesc*) &TM_3idqVVpbLQLcl3rcp2D9asw_6));
	T1_[1] = copyString(input);
	echoBinSafe(T1_, 2);
	nimln_(163, "push.nim");
	if (eqStrings(input, ((NimStringDesc*) &TM_3idqVVpbLQLcl3rcp2D9asw_7))) goto LA2_;
	if (eqStrings(input, ((NimStringDesc*) &TM_3idqVVpbLQLcl3rcp2D9asw_8))) goto LA3_;
	if (eqStrings(input, ((NimStringDesc*) &TM_3idqVVpbLQLcl3rcp2D9asw_9))) goto LA4_;
	if (eqStrings(input, ((NimStringDesc*) &TM_3idqVVpbLQLcl3rcp2D9asw_10))) goto LA5_;
	if (eqStrings(input, ((NimStringDesc*) &TM_3idqVVpbLQLcl3rcp2D9asw_11))) goto LA6_;
	goto LA7_;
	LA2_: ;
	{
		nimln_(165, "push.nim");
		result = ((tyEnum_InputAction_65PXn9bhXPOUlLz1qL3PCeQ) 0);
	}
	goto LA8_;
	LA3_: ;
	{
		nimln_(167, "push.nim");
		result = ((tyEnum_InputAction_65PXn9bhXPOUlLz1qL3PCeQ) 1);
	}
	goto LA8_;
	LA4_: ;
	{
		nimln_(169, "push.nim");
		result = ((tyEnum_InputAction_65PXn9bhXPOUlLz1qL3PCeQ) 2);
	}
	goto LA8_;
	LA5_: ;
	{
		nimln_(171, "push.nim");
		result = ((tyEnum_InputAction_65PXn9bhXPOUlLz1qL3PCeQ) 3);
	}
	goto LA8_;
	LA6_: ;
	{
		nimln_(173, "push.nim");
		result = ((tyEnum_InputAction_65PXn9bhXPOUlLz1qL3PCeQ) 4);
	}
	goto LA8_;
	LA7_: ;
	{
		nimln_(175, "push.nim");
		result = ((tyEnum_InputAction_65PXn9bhXPOUlLz1qL3PCeQ) 5);
	}
	LA8_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, hash_wja033thh0Z4NAd9bdBGScwtables)(tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw x) {
	NI result;
	nimfr_("hash", "hashes.nim");
	result = (NI)0;
	nimln_(129, "hashes.nim");
	result = x;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables)(NI hcode) {
	NIM_BOOL result;
	nimfr_("isFilled", "tableimpl.nim");
	result = (NIM_BOOL)0;
	nimln_(18, "tableimpl.nim");
	nimln_(398, "system.nim");
	nimln_(18, "tableimpl.nim");
	result = !((hcode == ((NI) 0)));
	popFrame();
	return result;
}

static N_INLINE(NI, nextTry_OLPhxSyW9bte5CwHzzQVhfAtables)(NI h, NI maxHash) {
	NI result;
	NI TM_3idqVVpbLQLcl3rcp2D9asw_16;
	nimfr_("nextTry", "tableimpl.nim");
	result = (NI)0;
	nimln_(28, "tableimpl.nim");
	TM_3idqVVpbLQLcl3rcp2D9asw_16 = addInt(h, ((NI) 1));
	result = (NI)((NI)(TM_3idqVVpbLQLcl3rcp2D9asw_16) & maxHash);
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, rawGet_AHdLKezz07NuzDUvZosDZgtables)(tyObject_Table_nIG4O9c9a3gnDGm0H0nP9aqvA t, tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw key, NI* hc) {
	NI result;
	NI h;
	NI T5_;
	NI TM_3idqVVpbLQLcl3rcp2D9asw_17;
	nimfr_("rawGet", "tableimpl.nim");
{	result = (NI)0;
	nimln_(53, "tableimpl.nim");
	(*hc) = hash_wja033thh0Z4NAd9bdBGScwtables(key);
	{
		if (!((*hc) == ((NI) 0))) goto LA3_;
		nimln_(45, "tableimpl.nim");
		(*hc) = ((NI) 314159265);
	}
	LA3_: ;
	nimln_(31, "tableimpl.nim");
	nimln_(116, "tables.nim");
	T5_ = (t.data ? (t.data->Sup.len-1) : -1);
	h = (NI)((*hc) & T5_);
	{
		nimln_(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL T8_;
			NI T15_;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			T8_ = (NIM_BOOL)0;
			T8_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(t.data->data[h].Field0);
			if (!T8_) goto LA7;
			nimln_(37, "tableimpl.nim");
			{
				NIM_BOOL T11_;
				T11_ = (NIM_BOOL)0;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T11_ = (t.data->data[h].Field0 == (*hc));
				if (!(T11_)) goto LA12_;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T11_ = (t.data->data[h].Field1 == key);
				LA12_: ;
				if (!T11_) goto LA13_;
				nimln_(38, "tableimpl.nim");
				result = h;
				goto BeforeRet_;
			}
			LA13_: ;
			nimln_(39, "tableimpl.nim");
			nimln_(116, "tables.nim");
			T15_ = (t.data ? (t.data->Sup.len-1) : -1);
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, T15_);
		} LA7: ;
	}
	nimln_(40, "tableimpl.nim");
	TM_3idqVVpbLQLcl3rcp2D9asw_17 = subInt(((NI) -1), h);
	result = (NI)(TM_3idqVVpbLQLcl3rcp2D9asw_17);
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, rawGetKnownHC_n60yivyEBqJdPM2o7lYUhQtables)(tyObject_Table_nIG4O9c9a3gnDGm0H0nP9aqvA t, tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw key, NI hc) {
	NI result;
	NI h;
	NI T1_;
	NI TM_3idqVVpbLQLcl3rcp2D9asw_18;
	nimfr_("rawGetKnownHC", "tableimpl.nim");
{	result = (NI)0;
	nimln_(31, "tableimpl.nim");
	nimln_(116, "tables.nim");
	T1_ = (t.data ? (t.data->Sup.len-1) : -1);
	h = (NI)(hc & T1_);
	{
		nimln_(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL T4_;
			NI T11_;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			T4_ = (NIM_BOOL)0;
			T4_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(t.data->data[h].Field0);
			if (!T4_) goto LA3;
			nimln_(37, "tableimpl.nim");
			{
				NIM_BOOL T7_;
				T7_ = (NIM_BOOL)0;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T7_ = (t.data->data[h].Field0 == hc);
				if (!(T7_)) goto LA8_;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T7_ = (t.data->data[h].Field1 == key);
				LA8_: ;
				if (!T7_) goto LA9_;
				nimln_(38, "tableimpl.nim");
				result = h;
				goto BeforeRet_;
			}
			LA9_: ;
			nimln_(39, "tableimpl.nim");
			nimln_(116, "tables.nim");
			T11_ = (t.data ? (t.data->Sup.len-1) : -1);
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, T11_);
		} LA3: ;
	}
	nimln_(40, "tableimpl.nim");
	TM_3idqVVpbLQLcl3rcp2D9asw_18 = subInt(((NI) -1), h);
	result = (NI)(TM_3idqVVpbLQLcl3rcp2D9asw_18);
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_NIMCALL(void, Marker_tyRef_pF0A5b9a9bWqyJfPW89cModmA)(void* p, NI op) {
	tyObject_PlayercolonObjectType__YKSlBm59bz8cnvLRFi6TueA* a;
	a = (tyObject_PlayercolonObjectType__YKSlBm59bz8cnvLRFi6TueA*)p;
}
static N_NIMCALL(void, Marker_tyRef_5m1ohdzyS0OmNkC7RPxo9bQ)(void* p, NI op) {
	tyObject_BoxcolonObjectType__CcD6IYPdn4nlPMYfEQhewQ* a;
	a = (tyObject_BoxcolonObjectType__CcD6IYPdn4nlPMYfEQhewQ*)p;
}
static N_NIMCALL(void, Marker_tyRef_LtDmL6a1ws79cyGkTS4ZDOQ)(void* p, NI op) {
	tyObject_BoxTargetcolonObjectType__RZuy9cwz9cfw8y9ab8un3pUpQ* a;
	a = (tyObject_BoxTargetcolonObjectType__RZuy9cwz9cfw8y9ab8un3pUpQ*)p;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(250, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(252, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(253, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim");
	nimln_(191, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(218, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(219, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim");
	nimln_(264, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(398, "system.nim");
		nimln_(264, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(265, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(398, "system.nim");
		nimln_(265, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(266, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, newMap_VJhoxGoZVbUbQ9cyCIktnLA)(tyObject_Map_bwPsPqooz39aY9cFequ9cPMZg* Result) {
	tyObject_PlayercolonObjectType__YKSlBm59bz8cnvLRFi6TueA* player;
	tyArray_O1t8Odh9cUegkP1sczBQjlA boxes;
	tyArray_PWHgkvTkJgyby9afHn9a1osw boxTargets;
	nimfr_("newMap", "push.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_bwPsPqooz39aY9cFequ9cPMZg_));
	nimln_(53, "push.nim");
	{
		tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA* e;
		NimStringDesc* T5_;
		if (!NIM_FALSE) goto LA3_;
		e = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*)0;
		nimln_(2811, "system.nim");
		e = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*) newObj((&NTI_yCEN9anxCD6mzBxGjuaRBdg_), sizeof(tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA));
		(*e).Sup.Sup.m_type = (&NTI_Gi06FkNeykJn7mrqRZYrkA_);
		nimln_(54, "push.nim");
		T5_ = (NimStringDesc*)0;
		T5_ = (*e).Sup.message; (*e).Sup.message = copyStringRC1(((NimStringDesc*) &TM_3idqVVpbLQLcl3rcp2D9asw_20));
		if (T5_) nimGCunrefNoCycle(T5_);
		nimln_(2806, "system.nim");
		asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
		nimln_(54, "push.nim");
		raiseException((Exception*)e, "ValueError");
	}
	LA3_: ;
	nimln_(56, "push.nim");
	player = new_Z9bPY53FJdVBzfJKSz2bGgA();
	memset((void*)boxes, 0, sizeof(boxes));
	memset((void*)boxTargets, 0, sizeof(boxTargets));
	nimln_(59, "push.nim");
	(*player).pos = nthCoord_YnKvJistBbyRII7Pq9ajnIA(((NI) 0), ((NI) 6), ((NI) 3));
	{
		NI iBox;
		NI i;
		iBox = (NI)0;
		nimln_(3519, "system.nim");
		i = ((NI) 0);
		{
			nimln_(3520, "system.nim");
			while (1) {
				NI TM_3idqVVpbLQLcl3rcp2D9asw_21;
				NI TM_3idqVVpbLQLcl3rcp2D9asw_22;
				NI TM_3idqVVpbLQLcl3rcp2D9asw_23;
				if (!(i < ((NI) 2))) goto LA8;
				nimln_(3521, "system.nim");
				iBox = i;
				if ((NU)(iBox) > (NU)(1)) raiseIndexError();
				nimln_(61, "push.nim");
				boxes[(iBox)- 0] = new_vJa1Px3VC82L38Sg03Basg();
				if ((NU)(iBox) > (NU)(1)) raiseIndexError();
				nimln_(62, "push.nim");
				boxTargets[(iBox)- 0] = new_pGC2AQ3Hz7ppk6U7Vccb3w();
				if ((NU)(iBox) > (NU)(1)) raiseIndexError();
				nimln_(63, "push.nim");
				TM_3idqVVpbLQLcl3rcp2D9asw_21 = addInt(iBox, ((NI) 1));
				(*boxes[(iBox)- 0]).pos = nthCoord_YnKvJistBbyRII7Pq9ajnIA((NI)(TM_3idqVVpbLQLcl3rcp2D9asw_21), ((NI) 6), ((NI) 3));
				if ((NU)(iBox) > (NU)(1)) raiseIndexError();
				nimln_(64, "push.nim");
				TM_3idqVVpbLQLcl3rcp2D9asw_22 = addInt(iBox, ((NI) 1));
				(*boxTargets[(iBox)- 0]).pos = nthCoord_YnKvJistBbyRII7Pq9ajnIA((NI)(TM_3idqVVpbLQLcl3rcp2D9asw_22), ((NI) 6), ((NI) 3));
				nimln_(3522, "system.nim");
				TM_3idqVVpbLQLcl3rcp2D9asw_23 = addInt(i, ((NI) 1));
				i = (NI)(TM_3idqVVpbLQLcl3rcp2D9asw_23);
			} LA8: ;
		}
	}
	nimln_(65, "push.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_bwPsPqooz39aY9cFequ9cPMZg_));
	unsureAsgnRef((void**) (&(*Result).player), player);
	genericAssign((void*)(*Result).boxes, (void*)boxes, (&NTI_O1t8Odh9cUegkP1sczBQjlA_));
	genericAssign((void*)(*Result).boxTargets, (void*)boxTargets, (&NTI_PWHgkvTkJgyby9afHn9a1osw_));
	popFrame();
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getVisualMap_RhT0OpkXSHhOHnnNAmrMfA)(tyObject_Map_bwPsPqooz39aY9cFequ9cPMZg* map) {
	NimStringDesc* result;
	tyArray_9addaGct6lvVwXAeOuCK73g visualMap;
	NI pX;
	NI pY;
	NimStringDesc* hBorder;
	NimStringDesc* T35_;
	nimfr_("getVisualMap", "push.nim");
	result = (NimStringDesc*)0;
	memset((void*)visualMap, 0, sizeof(visualMap));
	{
		NI iX;
		NI i;
		iX = (NI)0;
		nimln_(3519, "system.nim");
		i = ((NI) 0);
		{
			nimln_(3520, "system.nim");
			while (1) {
				NI TM_3idqVVpbLQLcl3rcp2D9asw_25;
				if (!(i < ((NI) 6))) goto LA3;
				nimln_(3521, "system.nim");
				iX = i;
				{
					NI iY;
					NI i_2;
					iY = (NI)0;
					nimln_(3519, "system.nim");
					i_2 = ((NI) 0);
					{
						nimln_(3520, "system.nim");
						while (1) {
							NI TM_3idqVVpbLQLcl3rcp2D9asw_24;
							if (!(i_2 < ((NI) 3))) goto LA6;
							nimln_(3521, "system.nim");
							iY = i_2;
							if ((NU)(iY) > (NU)(2)) raiseIndexError();
							if ((NU)(iX) > (NU)(5)) raiseIndexError();
							nimln_(125, "push.nim");
							visualMap[(iY)- 0][(iX)- 0] = 32;
							nimln_(3522, "system.nim");
							TM_3idqVVpbLQLcl3rcp2D9asw_24 = addInt(i_2, ((NI) 1));
							i_2 = (NI)(TM_3idqVVpbLQLcl3rcp2D9asw_24);
						} LA6: ;
					}
				}
				TM_3idqVVpbLQLcl3rcp2D9asw_25 = addInt(i, ((NI) 1));
				i = (NI)(TM_3idqVVpbLQLcl3rcp2D9asw_25);
			} LA3: ;
		}
	}
	{
		tyObject_BoxTargetcolonObjectType__RZuy9cwz9cfw8y9ab8un3pUpQ* boxTarget;
		tyArray_PWHgkvTkJgyby9afHn9a1osw colontmp_;
		NI i_3;
		boxTarget = (tyObject_BoxTargetcolonObjectType__RZuy9cwz9cfw8y9ab8un3pUpQ*)0;
		memset((void*)colontmp_, 0, sizeof(colontmp_));
		nimln_(128, "push.nim");
		memcpy((void*)colontmp_, (NIM_CONST void*)(*map).boxTargets, sizeof(colontmp_));
		nimln_(2199, "system.nim");
		i_3 = ((NI) 0);
		nimln_(2200, "system.nim");
		{
			if (!(((NI) (i_3)) <= ((NI) 1))) goto LA10_;
			{
				nimln_(2201, "system.nim");
				while (1) {
					NI TM_3idqVVpbLQLcl3rcp2D9asw_26;
					nimln_(2202, "system.nim");
					boxTarget = colontmp_[(i_3)- 0];
					if ((NU)((*boxTarget).pos.Field1) > (NU)(2)) raiseIndexError();
					if ((NU)((*boxTarget).pos.Field0) > (NU)(5)) raiseIndexError();
					nimln_(129, "push.nim");
					visualMap[((*boxTarget).pos.Field1)- 0][((*boxTarget).pos.Field0)- 0] = 46;
					nimln_(2203, "system.nim");
					{
						if (!(((NI) 1) <= ((NI) (i_3)))) goto LA16_;
						goto LA12;
					}
					LA16_: ;
					nimln_(2204, "system.nim");
					TM_3idqVVpbLQLcl3rcp2D9asw_26 = addInt(i_3, ((NI) 1));
					if (TM_3idqVVpbLQLcl3rcp2D9asw_26 < 0 || TM_3idqVVpbLQLcl3rcp2D9asw_26 > 1) raiseOverflow();
					i_3 = (NI)(TM_3idqVVpbLQLcl3rcp2D9asw_26);
				}
			} LA12: ;
		}
		LA10_: ;
	}
	nimln_(132, "push.nim");
	pX = (*(*map).player).pos.Field0;
	pY = (*(*map).player).pos.Field1;
	nimln_(133, "push.nim");
	if ((NU)(pY) > (NU)(2)) raiseIndexError();
	if ((NU)(pX) > (NU)(5)) raiseIndexError();
	switch (((NU8)(visualMap[(pY)- 0][(pX)- 0]))) {
	case 32:
	case 111:
	{
		if ((NU)(pY) > (NU)(2)) raiseIndexError();
		if ((NU)(pX) > (NU)(5)) raiseIndexError();
		nimln_(135, "push.nim");
		visualMap[(pY)- 0][(pX)- 0] = 80;
	}
	break;
	case 46:
	{
		if ((NU)(pY) > (NU)(2)) raiseIndexError();
		if ((NU)(pX) > (NU)(5)) raiseIndexError();
		nimln_(137, "push.nim");
		visualMap[(pY)- 0][(pX)- 0] = 82;
	}
	break;
	default:
	{
	}
	break;
	}
	{
		tyObject_BoxcolonObjectType__CcD6IYPdn4nlPMYfEQhewQ* box;
		tyArray_O1t8Odh9cUegkP1sczBQjlA colontmp__2;
		NI i_4;
		box = (tyObject_BoxcolonObjectType__CcD6IYPdn4nlPMYfEQhewQ*)0;
		memset((void*)colontmp__2, 0, sizeof(colontmp__2));
		nimln_(141, "push.nim");
		memcpy((void*)colontmp__2, (NIM_CONST void*)(*map).boxes, sizeof(colontmp__2));
		nimln_(2199, "system.nim");
		i_4 = ((NI) 0);
		nimln_(2200, "system.nim");
		{
			if (!(((NI) (i_4)) <= ((NI) 1))) goto LA24_;
			{
				nimln_(2201, "system.nim");
				while (1) {
					NI bX;
					NI bY;
					NI TM_3idqVVpbLQLcl3rcp2D9asw_27;
					nimln_(2202, "system.nim");
					box = colontmp__2[(i_4)- 0];
					nimln_(142, "push.nim");
					bX = (*box).pos.Field0;
					bY = (*box).pos.Field1;
					nimln_(143, "push.nim");
					if ((NU)(bY) > (NU)(2)) raiseIndexError();
					if ((NU)(bX) > (NU)(5)) raiseIndexError();
					switch (((NU8)(visualMap[(bY)- 0][(bX)- 0]))) {
					case 32:
					case 111:
					case 112:
					{
						if ((NU)(bY) > (NU)(2)) raiseIndexError();
						if ((NU)(bX) > (NU)(5)) raiseIndexError();
						nimln_(145, "push.nim");
						visualMap[(bY)- 0][(bX)- 0] = 111;
					}
					break;
					case 46:
					{
						if ((NU)(bY) > (NU)(2)) raiseIndexError();
						if ((NU)(bX) > (NU)(5)) raiseIndexError();
						nimln_(147, "push.nim");
						visualMap[(bY)- 0][(bX)- 0] = 64;
					}
					break;
					default:
					{
					}
					break;
					}
					nimln_(2203, "system.nim");
					{
						if (!(((NI) 1) <= ((NI) (i_4)))) goto LA33_;
						goto LA26;
					}
					LA33_: ;
					nimln_(2204, "system.nim");
					TM_3idqVVpbLQLcl3rcp2D9asw_27 = addInt(i_4, ((NI) 1));
					if (TM_3idqVVpbLQLcl3rcp2D9asw_27 < 0 || TM_3idqVVpbLQLcl3rcp2D9asw_27 > 1) raiseOverflow();
					i_4 = (NI)(TM_3idqVVpbLQLcl3rcp2D9asw_27);
				}
			} LA26: ;
		}
		LA24_: ;
	}
	nimln_(152, "push.nim");
	result = copyString(((NimStringDesc*) &TM_3idqVVpbLQLcl3rcp2D9asw_28));
	nimln_(153, "push.nim");
	hBorder = nsuRepeatChar(35, ((NI) 8));
	nimln_(155, "push.nim");
	T35_ = (NimStringDesc*)0;
	T35_ = rawNewString(hBorder->Sup.len + 1);
appendString(T35_, hBorder);
appendString(T35_, ((NimStringDesc*) &TM_3idqVVpbLQLcl3rcp2D9asw_29));
	result = resizeString(result, T35_->Sup.len + 0);
appendString(result, T35_);
	{
		NI iY_2;
		NI i_5;
		iY_2 = (NI)0;
		nimln_(3519, "system.nim");
		i_5 = ((NI) 0);
		{
			nimln_(3520, "system.nim");
			while (1) {
				NimStringDesc* T39_;
				NimStringDesc* T40_;
				NI TM_3idqVVpbLQLcl3rcp2D9asw_32;
				if (!(i_5 < ((NI) 3))) goto LA38;
				nimln_(3521, "system.nim");
				iY_2 = i_5;
				nimln_(157, "push.nim");
				T39_ = (NimStringDesc*)0;
				if ((NU)(iY_2) > (NU)(2)) raiseIndexError();
				T40_ = (NimStringDesc*)0;
				T40_ = join_nTMIi7o8Zy13sFPeiBsCQA(visualMap[(iY_2)- 0], 6, ((NimStringDesc*) &TM_3idqVVpbLQLcl3rcp2D9asw_28));
				T39_ = rawNewString(T40_->Sup.len + 3);
appendString(T39_, ((NimStringDesc*) &TM_3idqVVpbLQLcl3rcp2D9asw_30));
appendString(T39_, T40_);
appendString(T39_, ((NimStringDesc*) &TM_3idqVVpbLQLcl3rcp2D9asw_31));
				result = resizeString(result, T39_->Sup.len + 0);
appendString(result, T39_);
				nimln_(3522, "system.nim");
				TM_3idqVVpbLQLcl3rcp2D9asw_32 = addInt(i_5, ((NI) 1));
				i_5 = (NI)(TM_3idqVVpbLQLcl3rcp2D9asw_32);
			} LA38: ;
		}
	}
	nimln_(158, "push.nim");
	result = resizeString(result, hBorder->Sup.len + 0);
appendString(result, hBorder);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, draw_Ubbw9cPGosWWYaTZuFFYaVw)(tyObject_Map_bwPsPqooz39aY9cFequ9cPMZg* map) {
	tyArray_nHXaesL0DJZHyVS07ARPRA T1_;
	nimfr_("draw", "push.nim");
	nimln_(194, "push.nim");
	memset((void*)T1_, 0, sizeof(T1_));
	T1_[0] = getVisualMap_RhT0OpkXSHhOHnnNAmrMfA(map);
	echoBinSafe(T1_, 1);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NI, getIBoxAt_HWq9axnMLwPIY9bd6Ojr39bhA)(tyObject_Map_bwPsPqooz39aY9cFequ9cPMZg* map, tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ pos) {
	NI result;
	nimfr_("getIBoxAt", "push.nim");
{	result = (NI)0;
	{
		NI iBox;
		tyObject_BoxcolonObjectType__CcD6IYPdn4nlPMYfEQhewQ* box;
		tyArray_O1t8Odh9cUegkP1sczBQjlA colontmp_;
		NI i;
		iBox = (NI)0;
		box = (tyObject_BoxcolonObjectType__CcD6IYPdn4nlPMYfEQhewQ*)0;
		memset((void*)colontmp_, 0, sizeof(colontmp_));
		nimln_(73, "push.nim");
		memcpy((void*)colontmp_, (NIM_CONST void*)(*map).boxes, sizeof(colontmp_));
		nimln_(2266, "system.nim");
		i = ((NI) 0);
		nimln_(2267, "system.nim");
		{
			if (!(((NI) (i)) <= ((NI) 1))) goto LA4_;
			{
				nimln_(2268, "system.nim");
				while (1) {
					NI TM_3idqVVpbLQLcl3rcp2D9asw_33;
					nimln_(2269, "system.nim");
					iBox = i;
					box = colontmp_[(i)- 0];
					nimln_(74, "push.nim");
					{
						NIM_BOOL T10_;
						T10_ = (NIM_BOOL)0;
						T10_ = eqeq__GMdYAiXVYFtXgUAy83DYgg((*box).pos, pos);
						if (!T10_) goto LA11_;
						nimln_(75, "push.nim");
						result = ((NI) (iBox));
						goto BeforeRet_;
					}
					LA11_: ;
					nimln_(2270, "system.nim");
					{
						if (!(((NI) 1) <= ((NI) (i)))) goto LA15_;
						goto LA6;
					}
					LA15_: ;
					nimln_(2271, "system.nim");
					TM_3idqVVpbLQLcl3rcp2D9asw_33 = addInt(i, ((NI) 1));
					if (TM_3idqVVpbLQLcl3rcp2D9asw_33 < 0 || TM_3idqVVpbLQLcl3rcp2D9asw_33 > 1) raiseOverflow();
					i = (NI)(TM_3idqVVpbLQLcl3rcp2D9asw_33);
				}
			} LA6: ;
		}
		LA4_: ;
	}
	nimln_(76, "push.nim");
	result = ((NI) -1);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, checkBoxOnTarget_Ev69bcTWOnjGjYUgAreqB7A)(tyObject_Map_bwPsPqooz39aY9cFequ9cPMZg* map) {
	NIM_BOOL result;
	nimfr_("checkBoxOnTarget", "push.nim");
{	result = (NIM_BOOL)0;
	{
		tyObject_BoxTargetcolonObjectType__RZuy9cwz9cfw8y9ab8un3pUpQ* boxTarget;
		tyArray_PWHgkvTkJgyby9afHn9a1osw colontmp_;
		NI i;
		boxTarget = (tyObject_BoxTargetcolonObjectType__RZuy9cwz9cfw8y9ab8un3pUpQ*)0;
		memset((void*)colontmp_, 0, sizeof(colontmp_));
		nimln_(114, "push.nim");
		memcpy((void*)colontmp_, (NIM_CONST void*)(*map).boxTargets, sizeof(colontmp_));
		nimln_(2199, "system.nim");
		i = ((NI) 0);
		nimln_(2200, "system.nim");
		{
			if (!(((NI) (i)) <= ((NI) 1))) goto LA4_;
			{
				nimln_(2201, "system.nim");
				while (1) {
					NI TM_3idqVVpbLQLcl3rcp2D9asw_34;
					nimln_(2202, "system.nim");
					boxTarget = colontmp_[(i)- 0];
					nimln_(115, "push.nim");
					{
						NI T10_;
						T10_ = (NI)0;
						T10_ = getIBoxAt_HWq9axnMLwPIY9bd6Ojr39bhA(map, (*boxTarget).pos);
						if (!!((((NI) 0) <= T10_))) goto LA11_;
						nimln_(116, "push.nim");
						result = NIM_FALSE;
						goto BeforeRet_;
					}
					LA11_: ;
					nimln_(2203, "system.nim");
					{
						if (!(((NI) 1) <= ((NI) (i)))) goto LA15_;
						goto LA6;
					}
					LA15_: ;
					nimln_(2204, "system.nim");
					TM_3idqVVpbLQLcl3rcp2D9asw_34 = addInt(i, ((NI) 1));
					if (TM_3idqVVpbLQLcl3rcp2D9asw_34 < 0 || TM_3idqVVpbLQLcl3rcp2D9asw_34 > 1) raiseOverflow();
					i = (NI)(TM_3idqVVpbLQLcl3rcp2D9asw_34);
				}
			} LA6: ;
		}
		LA4_: ;
	}
	nimln_(117, "push.nim");
	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, colonanonymous__8llUUXRaS7N2Rhect6F0PQ)(NI value, NI size) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	nimfr_(":anonymous", "push.nim");
	result = (NIM_BOOL)0;
	nimln_(83, "push.nim");
	T1_ = (NIM_BOOL)0;
	T1_ = (((NI) 0) <= value);
	if (!(T1_)) goto LA2_;
	T1_ = (value < size);
	LA2_: ;
	result = T1_;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyTuple_qmFwV9bFQ9a4cxfYwLzDR0lQ, getDestinStatus_U3MREanvOWwZ9a3ts14lQtA)(tyObject_Map_bwPsPqooz39aY9cFequ9cPMZg* map, tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ destin) {
	tyTuple_qmFwV9bFQ9a4cxfYwLzDR0lQ result;
	tyProc_RqErSzKvAG3vZYqc85mVBA cw;
	NI iBox;
	nimfr_("getDestinStatus", "push.nim");
{	memset((void*)(&result), 0, sizeof(result));
	nimln_(83, "push.nim");
	cw = colonanonymous__8llUUXRaS7N2Rhect6F0PQ;
	nimln_(84, "push.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = cw(destin.Field0, ((NI) 6));
		if (!(T3_)) goto LA4_;
		T3_ = cw(destin.Field1, ((NI) 3));
		LA4_: ;
		if (!!(T3_)) goto LA5_;
		nimln_(85, "push.nim");
		result = TM_3idqVVpbLQLcl3rcp2D9asw_37;
		goto BeforeRet_;
	}
	LA5_: ;
	nimln_(88, "push.nim");
	iBox = getIBoxAt_HWq9axnMLwPIY9bd6Ojr39bhA(map, destin);
	nimln_(89, "push.nim");
	{
		if (!(iBox == ((NI) -1))) goto LA9_;
		nimln_(90, "push.nim");
		result = TM_3idqVVpbLQLcl3rcp2D9asw_38;
		goto BeforeRet_;
	}
	LA9_: ;
	nimln_(91, "push.nim");
	result.Field0 = ((tyEnum_DestinStatus_uWnJ20JvX6gkNBB7pR6M6w) 2);
	result.Field1 = iBox;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, movePlayer_hHlfeVjp62CR2MvBikJH2g)(tyObject_Map_bwPsPqooz39aY9cFequ9cPMZg* map, tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw direct) {
	tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ destin;
	tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ T1_;
	tyTuple_qmFwV9bFQ9a4cxfYwLzDR0lQ destinStatus;
	nimfr_("movePlayer", "push.nim");
	nimln_(95, "push.nim");
	nimln_(318, "tables.nim");
	T1_ = X5BX5D__M8fLPtDcT9aAoQyfTfVp6TA(TM_3idqVVpbLQLcl3rcp2D9asw_35, direct);
	destin = plus__V69cd9cWTLH4esNl9b6zfgteA((*(*map).player).pos, T1_);
	nimln_(96, "push.nim");
	destinStatus = getDestinStatus_U3MREanvOWwZ9a3ts14lQtA(map, destin);
	nimln_(97, "push.nim");
	switch (destinStatus.Field0) {
	case ((tyEnum_DestinStatus_uWnJ20JvX6gkNBB7pR6M6w) 0):
	{
		nimln_(99, "push.nim");
		(*(*map).player).pos = destin;
	}
	break;
	case ((tyEnum_DestinStatus_uWnJ20JvX6gkNBB7pR6M6w) 1):
	{
	}
	break;
	case ((tyEnum_DestinStatus_uWnJ20JvX6gkNBB7pR6M6w) 2):
	{
		tyObject_BoxcolonObjectType__CcD6IYPdn4nlPMYfEQhewQ* box;
		tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ boxDestin;
		tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ T5_;
		tyTuple_qmFwV9bFQ9a4cxfYwLzDR0lQ boxDestinStatus;
		nimln_(103, "push.nim");
		if ((NU)(destinStatus.Field1) > (NU)(1)) raiseIndexError();
		box = (*map).boxes[(destinStatus.Field1)- 0];
		nimln_(104, "push.nim");
		nimln_(318, "tables.nim");
		T5_ = X5BX5D__M8fLPtDcT9aAoQyfTfVp6TA(TM_3idqVVpbLQLcl3rcp2D9asw_35, direct);
		boxDestin = plus__V69cd9cWTLH4esNl9b6zfgteA((*box).pos, T5_);
		nimln_(105, "push.nim");
		boxDestinStatus = getDestinStatus_U3MREanvOWwZ9a3ts14lQtA(map, boxDestin);
		nimln_(106, "push.nim");
		switch (boxDestinStatus.Field0) {
		case ((tyEnum_DestinStatus_uWnJ20JvX6gkNBB7pR6M6w) 0):
		{
			nimln_(108, "push.nim");
			(*(*map).player).pos = destin;
			nimln_(109, "push.nim");
			(*box).pos = boxDestin;
		}
		break;
		case ((tyEnum_DestinStatus_uWnJ20JvX6gkNBB7pR6M6w) 1):
		case ((tyEnum_DestinStatus_uWnJ20JvX6gkNBB7pR6M6w) 2):
		{
		}
		break;
		}
	}
	break;
	}
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, updateGame_o1gLFsrKoVd9cUlm4BRafRQ)(tyObject_Map_bwPsPqooz39aY9cFequ9cPMZg* map, tyEnum_InputAction_65PXn9bhXPOUlLz1qL3PCeQ inputAction) {
	nimfr_("updateGame", "push.nim");
	nimln_(179, "push.nim");
	switch (inputAction) {
	case ((tyEnum_InputAction_65PXn9bhXPOUlLz1qL3PCeQ) 0):
	{
		nimln_(181, "push.nim");
		movePlayer_hHlfeVjp62CR2MvBikJH2g(map, ((tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw) 0));
	}
	break;
	case ((tyEnum_InputAction_65PXn9bhXPOUlLz1qL3PCeQ) 1):
	{
		nimln_(183, "push.nim");
		movePlayer_hHlfeVjp62CR2MvBikJH2g(map, ((tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw) 1));
	}
	break;
	case ((tyEnum_InputAction_65PXn9bhXPOUlLz1qL3PCeQ) 2):
	{
		nimln_(185, "push.nim");
		movePlayer_hHlfeVjp62CR2MvBikJH2g(map, ((tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw) 2));
	}
	break;
	case ((tyEnum_InputAction_65PXn9bhXPOUlLz1qL3PCeQ) 3):
	{
		nimln_(187, "push.nim");
		movePlayer_hHlfeVjp62CR2MvBikJH2g(map, ((tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw) 3));
	}
	break;
	case ((tyEnum_InputAction_65PXn9bhXPOUlLz1qL3PCeQ) 4):
	{
		nimln_(1500, "system.nim");
		exit(((NI) 0));
	}
	break;
	case ((tyEnum_InputAction_65PXn9bhXPOUlLz1qL3PCeQ) 5):
	{
	}
	break;
	}
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, unknown_pushInit000)(void) {
	nimfr_("push", "push.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, unknown_pushDatInit000)(void) {
static TNimNode* TM_3idqVVpbLQLcl3rcp2D9asw_12[5];
NI TM_3idqVVpbLQLcl3rcp2D9asw_14;
static char* NIM_CONST TM_3idqVVpbLQLcl3rcp2D9asw_13[5] = {
"up", 
"down", 
"left", 
"right", 
"immobile"};
static TNimNode* TM_3idqVVpbLQLcl3rcp2D9asw_15[2];
static TNimNode* TM_3idqVVpbLQLcl3rcp2D9asw_19[3];
static TNimNode TM_3idqVVpbLQLcl3rcp2D9asw_0[16];
NTI_cLjoWhgzLRaR7YLGawE7Uw_.size = sizeof(tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw);
NTI_cLjoWhgzLRaR7YLGawE7Uw_.kind = 14;
NTI_cLjoWhgzLRaR7YLGawE7Uw_.base = 0;
NTI_cLjoWhgzLRaR7YLGawE7Uw_.flags = 3;
for (TM_3idqVVpbLQLcl3rcp2D9asw_14 = 0; TM_3idqVVpbLQLcl3rcp2D9asw_14 < 5; TM_3idqVVpbLQLcl3rcp2D9asw_14++) {
TM_3idqVVpbLQLcl3rcp2D9asw_0[TM_3idqVVpbLQLcl3rcp2D9asw_14+0].kind = 1;
TM_3idqVVpbLQLcl3rcp2D9asw_0[TM_3idqVVpbLQLcl3rcp2D9asw_14+0].offset = TM_3idqVVpbLQLcl3rcp2D9asw_14;
TM_3idqVVpbLQLcl3rcp2D9asw_0[TM_3idqVVpbLQLcl3rcp2D9asw_14+0].name = TM_3idqVVpbLQLcl3rcp2D9asw_13[TM_3idqVVpbLQLcl3rcp2D9asw_14];
TM_3idqVVpbLQLcl3rcp2D9asw_12[TM_3idqVVpbLQLcl3rcp2D9asw_14] = &TM_3idqVVpbLQLcl3rcp2D9asw_0[TM_3idqVVpbLQLcl3rcp2D9asw_14+0];
}
TM_3idqVVpbLQLcl3rcp2D9asw_0[5].len = 5; TM_3idqVVpbLQLcl3rcp2D9asw_0[5].kind = 2; TM_3idqVVpbLQLcl3rcp2D9asw_0[5].sons = &TM_3idqVVpbLQLcl3rcp2D9asw_12[0];
NTI_cLjoWhgzLRaR7YLGawE7Uw_.node = &TM_3idqVVpbLQLcl3rcp2D9asw_0[5];
NTI_1v9bKyksXWMsm0vNwmZ4EuQ_.size = sizeof(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ);
NTI_1v9bKyksXWMsm0vNwmZ4EuQ_.kind = 18;
NTI_1v9bKyksXWMsm0vNwmZ4EuQ_.base = 0;
NTI_1v9bKyksXWMsm0vNwmZ4EuQ_.flags = 3;
TM_3idqVVpbLQLcl3rcp2D9asw_15[0] = &TM_3idqVVpbLQLcl3rcp2D9asw_0[7];
TM_3idqVVpbLQLcl3rcp2D9asw_0[7].kind = 1;
TM_3idqVVpbLQLcl3rcp2D9asw_0[7].offset = offsetof(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ, Field0);
TM_3idqVVpbLQLcl3rcp2D9asw_0[7].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_3idqVVpbLQLcl3rcp2D9asw_0[7].name = "Field0";
TM_3idqVVpbLQLcl3rcp2D9asw_15[1] = &TM_3idqVVpbLQLcl3rcp2D9asw_0[8];
TM_3idqVVpbLQLcl3rcp2D9asw_0[8].kind = 1;
TM_3idqVVpbLQLcl3rcp2D9asw_0[8].offset = offsetof(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ, Field1);
TM_3idqVVpbLQLcl3rcp2D9asw_0[8].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_3idqVVpbLQLcl3rcp2D9asw_0[8].name = "Field1";
TM_3idqVVpbLQLcl3rcp2D9asw_0[6].len = 2; TM_3idqVVpbLQLcl3rcp2D9asw_0[6].kind = 2; TM_3idqVVpbLQLcl3rcp2D9asw_0[6].sons = &TM_3idqVVpbLQLcl3rcp2D9asw_15[0];
NTI_1v9bKyksXWMsm0vNwmZ4EuQ_.node = &TM_3idqVVpbLQLcl3rcp2D9asw_0[6];
NTI_bwPsPqooz39aY9cFequ9cPMZg_.size = sizeof(tyObject_Map_bwPsPqooz39aY9cFequ9cPMZg);
NTI_bwPsPqooz39aY9cFequ9cPMZg_.kind = 18;
NTI_bwPsPqooz39aY9cFequ9cPMZg_.base = 0;
NTI_bwPsPqooz39aY9cFequ9cPMZg_.flags = 2;
TM_3idqVVpbLQLcl3rcp2D9asw_19[0] = &TM_3idqVVpbLQLcl3rcp2D9asw_0[10];
NTI_YKSlBm59bz8cnvLRFi6TueA_.size = sizeof(tyObject_PlayercolonObjectType__YKSlBm59bz8cnvLRFi6TueA);
NTI_YKSlBm59bz8cnvLRFi6TueA_.kind = 18;
NTI_YKSlBm59bz8cnvLRFi6TueA_.base = 0;
NTI_YKSlBm59bz8cnvLRFi6TueA_.flags = 3;
TM_3idqVVpbLQLcl3rcp2D9asw_0[11].kind = 1;
TM_3idqVVpbLQLcl3rcp2D9asw_0[11].offset = offsetof(tyObject_PlayercolonObjectType__YKSlBm59bz8cnvLRFi6TueA, pos);
TM_3idqVVpbLQLcl3rcp2D9asw_0[11].typ = (&NTI_1v9bKyksXWMsm0vNwmZ4EuQ_);
TM_3idqVVpbLQLcl3rcp2D9asw_0[11].name = "pos";
NTI_YKSlBm59bz8cnvLRFi6TueA_.node = &TM_3idqVVpbLQLcl3rcp2D9asw_0[11];
NTI_pF0A5b9a9bWqyJfPW89cModmA_.size = sizeof(tyObject_PlayercolonObjectType__YKSlBm59bz8cnvLRFi6TueA*);
NTI_pF0A5b9a9bWqyJfPW89cModmA_.kind = 22;
NTI_pF0A5b9a9bWqyJfPW89cModmA_.base = (&NTI_YKSlBm59bz8cnvLRFi6TueA_);
NTI_pF0A5b9a9bWqyJfPW89cModmA_.flags = 2;
NTI_pF0A5b9a9bWqyJfPW89cModmA_.marker = Marker_tyRef_pF0A5b9a9bWqyJfPW89cModmA;
TM_3idqVVpbLQLcl3rcp2D9asw_0[10].kind = 1;
TM_3idqVVpbLQLcl3rcp2D9asw_0[10].offset = offsetof(tyObject_Map_bwPsPqooz39aY9cFequ9cPMZg, player);
TM_3idqVVpbLQLcl3rcp2D9asw_0[10].typ = (&NTI_pF0A5b9a9bWqyJfPW89cModmA_);
TM_3idqVVpbLQLcl3rcp2D9asw_0[10].name = "player";
TM_3idqVVpbLQLcl3rcp2D9asw_19[1] = &TM_3idqVVpbLQLcl3rcp2D9asw_0[12];
NTI_CcD6IYPdn4nlPMYfEQhewQ_.size = sizeof(tyObject_BoxcolonObjectType__CcD6IYPdn4nlPMYfEQhewQ);
NTI_CcD6IYPdn4nlPMYfEQhewQ_.kind = 18;
NTI_CcD6IYPdn4nlPMYfEQhewQ_.base = 0;
NTI_CcD6IYPdn4nlPMYfEQhewQ_.flags = 3;
TM_3idqVVpbLQLcl3rcp2D9asw_0[13].kind = 1;
TM_3idqVVpbLQLcl3rcp2D9asw_0[13].offset = offsetof(tyObject_BoxcolonObjectType__CcD6IYPdn4nlPMYfEQhewQ, pos);
TM_3idqVVpbLQLcl3rcp2D9asw_0[13].typ = (&NTI_1v9bKyksXWMsm0vNwmZ4EuQ_);
TM_3idqVVpbLQLcl3rcp2D9asw_0[13].name = "pos";
NTI_CcD6IYPdn4nlPMYfEQhewQ_.node = &TM_3idqVVpbLQLcl3rcp2D9asw_0[13];
NTI_5m1ohdzyS0OmNkC7RPxo9bQ_.size = sizeof(tyObject_BoxcolonObjectType__CcD6IYPdn4nlPMYfEQhewQ*);
NTI_5m1ohdzyS0OmNkC7RPxo9bQ_.kind = 22;
NTI_5m1ohdzyS0OmNkC7RPxo9bQ_.base = (&NTI_CcD6IYPdn4nlPMYfEQhewQ_);
NTI_5m1ohdzyS0OmNkC7RPxo9bQ_.flags = 2;
NTI_5m1ohdzyS0OmNkC7RPxo9bQ_.marker = Marker_tyRef_5m1ohdzyS0OmNkC7RPxo9bQ;
NTI_O1t8Odh9cUegkP1sczBQjlA_.size = sizeof(tyArray_O1t8Odh9cUegkP1sczBQjlA);
NTI_O1t8Odh9cUegkP1sczBQjlA_.kind = 16;
NTI_O1t8Odh9cUegkP1sczBQjlA_.base = (&NTI_5m1ohdzyS0OmNkC7RPxo9bQ_);
NTI_O1t8Odh9cUegkP1sczBQjlA_.flags = 2;
TM_3idqVVpbLQLcl3rcp2D9asw_0[12].kind = 1;
TM_3idqVVpbLQLcl3rcp2D9asw_0[12].offset = offsetof(tyObject_Map_bwPsPqooz39aY9cFequ9cPMZg, boxes);
TM_3idqVVpbLQLcl3rcp2D9asw_0[12].typ = (&NTI_O1t8Odh9cUegkP1sczBQjlA_);
TM_3idqVVpbLQLcl3rcp2D9asw_0[12].name = "boxes";
TM_3idqVVpbLQLcl3rcp2D9asw_19[2] = &TM_3idqVVpbLQLcl3rcp2D9asw_0[14];
NTI_RZuy9cwz9cfw8y9ab8un3pUpQ_.size = sizeof(tyObject_BoxTargetcolonObjectType__RZuy9cwz9cfw8y9ab8un3pUpQ);
NTI_RZuy9cwz9cfw8y9ab8un3pUpQ_.kind = 18;
NTI_RZuy9cwz9cfw8y9ab8un3pUpQ_.base = 0;
NTI_RZuy9cwz9cfw8y9ab8un3pUpQ_.flags = 3;
TM_3idqVVpbLQLcl3rcp2D9asw_0[15].kind = 1;
TM_3idqVVpbLQLcl3rcp2D9asw_0[15].offset = offsetof(tyObject_BoxTargetcolonObjectType__RZuy9cwz9cfw8y9ab8un3pUpQ, pos);
TM_3idqVVpbLQLcl3rcp2D9asw_0[15].typ = (&NTI_1v9bKyksXWMsm0vNwmZ4EuQ_);
TM_3idqVVpbLQLcl3rcp2D9asw_0[15].name = "pos";
NTI_RZuy9cwz9cfw8y9ab8un3pUpQ_.node = &TM_3idqVVpbLQLcl3rcp2D9asw_0[15];
NTI_LtDmL6a1ws79cyGkTS4ZDOQ_.size = sizeof(tyObject_BoxTargetcolonObjectType__RZuy9cwz9cfw8y9ab8un3pUpQ*);
NTI_LtDmL6a1ws79cyGkTS4ZDOQ_.kind = 22;
NTI_LtDmL6a1ws79cyGkTS4ZDOQ_.base = (&NTI_RZuy9cwz9cfw8y9ab8un3pUpQ_);
NTI_LtDmL6a1ws79cyGkTS4ZDOQ_.flags = 2;
NTI_LtDmL6a1ws79cyGkTS4ZDOQ_.marker = Marker_tyRef_LtDmL6a1ws79cyGkTS4ZDOQ;
NTI_PWHgkvTkJgyby9afHn9a1osw_.size = sizeof(tyArray_PWHgkvTkJgyby9afHn9a1osw);
NTI_PWHgkvTkJgyby9afHn9a1osw_.kind = 16;
NTI_PWHgkvTkJgyby9afHn9a1osw_.base = (&NTI_LtDmL6a1ws79cyGkTS4ZDOQ_);
NTI_PWHgkvTkJgyby9afHn9a1osw_.flags = 2;
TM_3idqVVpbLQLcl3rcp2D9asw_0[14].kind = 1;
TM_3idqVVpbLQLcl3rcp2D9asw_0[14].offset = offsetof(tyObject_Map_bwPsPqooz39aY9cFequ9cPMZg, boxTargets);
TM_3idqVVpbLQLcl3rcp2D9asw_0[14].typ = (&NTI_PWHgkvTkJgyby9afHn9a1osw_);
TM_3idqVVpbLQLcl3rcp2D9asw_0[14].name = "boxTargets";
TM_3idqVVpbLQLcl3rcp2D9asw_0[9].len = 3; TM_3idqVVpbLQLcl3rcp2D9asw_0[9].kind = 2; TM_3idqVVpbLQLcl3rcp2D9asw_0[9].sons = &TM_3idqVVpbLQLcl3rcp2D9asw_19[0];
NTI_bwPsPqooz39aY9cFequ9cPMZg_.node = &TM_3idqVVpbLQLcl3rcp2D9asw_0[9];
}

