/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/allosteric/.choosenim/toolchains/nim-0.18.0/lib -o /media/allosteric/Data/Arts/nim/BeforeGamer/Push/src/nimcache/push.o /media/allosteric/Data/Arts/nim/BeforeGamer/Push/src/nimcache/push.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_BoxcolonObjectType__CcD6IYPdn4nlPMYfEQhewQ tyObject_BoxcolonObjectType__CcD6IYPdn4nlPMYfEQhewQ;
typedef struct tyObject_MapcolonObjectType__4y9b8sKN9bsYOudkhZrNpitg tyObject_MapcolonObjectType__4y9b8sKN9bsYOudkhZrNpitg;
typedef struct tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tySequence_uB9b75OUPRENsBAu4AnoePA tySequence_uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_PlayercolonObjectType__YKSlBm59bz8cnvLRFi6TueA tyObject_PlayercolonObjectType__YKSlBm59bz8cnvLRFi6TueA;
typedef struct tySequence_qP006YpEnVuz2e9aGF9cMpHw tySequence_qP006YpEnVuz2e9aGF9cMpHw;
typedef struct tySequence_48htkG9cO2D6ATmPMpFeuow tySequence_48htkG9cO2D6ATmPMpFeuow;
typedef struct tyObject_BoxTargetcolonObjectType__RZuy9cwz9cfw8y9ab8un3pUpQ tyObject_BoxTargetcolonObjectType__RZuy9cwz9cfw8y9ab8un3pUpQ;
typedef struct tySequence_n1lfu84YYZHtqOit4XK9a2Q tySequence_n1lfu84YYZHtqOit4XK9a2Q;
typedef struct tyObject_ObstaclecolonObjectType__MfxUXOb9a5rFWMp79aQmNWqA tyObject_ObstaclecolonObjectType__MfxUXOb9a5rFWMp79aQmNWqA;
typedef struct tyTuple_qmFwV9bFQ9a4cxfYwLzDR0lQ tyTuple_qmFwV9bFQ9a4cxfYwLzDR0lQ;
typedef struct tyObject_Table_nIG4O9c9a3gnDGm0H0nP9aqvA tyObject_Table_nIG4O9c9a3gnDGm0H0nP9aqvA;
typedef struct tySequence_y9aTBJ79cxanGa2fAuei6iIg tySequence_y9aTBJ79cxanGa2fAuei6iIg;
typedef struct tyTuple_Yt1nTvhqbfseJu4tLVyjRw tyTuple_Yt1nTvhqbfseJu4tLVyjRw;
typedef struct tySequence_hmk4GiF9cJpv29aUeXPYPGfA tySequence_hmk4GiF9cJpv29aUeXPYPGfA;
typedef struct tySequence_lBgZ7a89beZGYPl8PiANMTA tySequence_lBgZ7a89beZGYPl8PiANMTA;
typedef struct tyTuple_DTy5no9cl66GOLoMhrMJm8A tyTuple_DTy5no9cl66GOLoMhrMJm8A;
typedef struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
struct tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ {
NI Field0;
NI Field1;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_BoxcolonObjectType__CcD6IYPdn4nlPMYfEQhewQ {
tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ pos;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
struct tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA {
  Exception Sup;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct tyObject_PlayercolonObjectType__YKSlBm59bz8cnvLRFi6TueA {
tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ pos;
};
struct tyObject_BoxTargetcolonObjectType__RZuy9cwz9cfw8y9ab8un3pUpQ {
tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ pos;
};
struct tyObject_ObstaclecolonObjectType__MfxUXOb9a5rFWMp79aQmNWqA {
tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ pos;
};
struct tyObject_MapcolonObjectType__4y9b8sKN9bsYOudkhZrNpitg {
NI height;
NI width;
tyObject_PlayercolonObjectType__YKSlBm59bz8cnvLRFi6TueA* player;
NI nBox;
tySequence_qP006YpEnVuz2e9aGF9cMpHw* boxes;
tySequence_48htkG9cO2D6ATmPMpFeuow* boxTargets;
tySequence_n1lfu84YYZHtqOit4XK9a2Q* obstacles;
};
typedef NU8 tyEnum_DestinStatus_uWnJ20JvX6gkNBB7pR6M6w;
struct tyTuple_qmFwV9bFQ9a4cxfYwLzDR0lQ {
tyEnum_DestinStatus_uWnJ20JvX6gkNBB7pR6M6w Field0;
NI Field1;
};
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc_RqErSzKvAG3vZYqc85mVBA) (NI value, NI size);
typedef NU8 tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw;
struct tyObject_Table_nIG4O9c9a3gnDGm0H0nP9aqvA {
tySequence_y9aTBJ79cxanGa2fAuei6iIg* data;
NI counter;
};
struct tyTuple_Yt1nTvhqbfseJu4tLVyjRw {
NI Field0;
tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw Field1;
tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ Field2;
};
typedef NU8 tyEnum_InputAction_65PXn9bhXPOUlLz1qL3PCeQ;
typedef NimStringDesc* tyArray_Re75IspeoxXy2oCZHwcRrA[2];
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyTuple_DTy5no9cl66GOLoMhrMJm8A {
tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw Field0;
tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ Field1;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_qP006YpEnVuz2e9aGF9cMpHw {
  TGenericSeq Sup;
  tyObject_BoxcolonObjectType__CcD6IYPdn4nlPMYfEQhewQ* data[SEQ_DECL_SIZE];
};
struct tySequence_48htkG9cO2D6ATmPMpFeuow {
  TGenericSeq Sup;
  tyObject_BoxTargetcolonObjectType__RZuy9cwz9cfw8y9ab8un3pUpQ* data[SEQ_DECL_SIZE];
};
struct tySequence_n1lfu84YYZHtqOit4XK9a2Q {
  TGenericSeq Sup;
  tyObject_ObstaclecolonObjectType__MfxUXOb9a5rFWMp79aQmNWqA* data[SEQ_DECL_SIZE];
};
struct tySequence_y9aTBJ79cxanGa2fAuei6iIg {
  TGenericSeq Sup;
  tyTuple_Yt1nTvhqbfseJu4tLVyjRw data[SEQ_DECL_SIZE];
};
struct tySequence_lBgZ7a89beZGYPl8PiANMTA {
  TGenericSeq Sup;
  NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tySequence_hmk4GiF9cJpv29aUeXPYPGfA {
  TGenericSeq Sup;
  tySequence_lBgZ7a89beZGYPl8PiANMTA* data[SEQ_DECL_SIZE];
};
struct tySequence_uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ, nthCoord_YnKvJistBbyRII7Pq9ajnIA)(NI n, NI width, NI height);
static N_INLINE(NI, modInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ, plus__V69cd9cWTLH4esNl9b6zfgteA)(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ pos0, tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ pos1);
static N_INLINE(NI, addInt)(NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__mr9aVLAUz5GU2Vb6MCHzy5g)(tyObject_BoxcolonObjectType__CcD6IYPdn4nlPMYfEQhewQ* box);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__76rXyWcsgGy3rg1rEcHNNw)(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ x);
N_LIB_PRIVATE N_NIMCALL(tyObject_MapcolonObjectType__4y9b8sKN9bsYOudkhZrNpitg*, newMap_vYQo9bUurZNloWZ8jelysMQ)(NI width, NI height, NI nBox, NI nObs);
N_NIMCALL(NI, mulInt)(NI a, NI b);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_LIB_PRIVATE N_NIMCALL(tyObject_PlayercolonObjectType__YKSlBm59bz8cnvLRFi6TueA*, new_Z9bPY53FJdVBzfJKSz2bGgA)(void);
static N_NIMCALL(void, Marker_tyRef_pF0A5b9a9bWqyJfPW89cModmA)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(tySequence_qP006YpEnVuz2e9aGF9cMpHw*, newSeq_pkhiL4PxQF9bHsBsNmjE4zA)(NI len);
static N_NIMCALL(void, Marker_tyRef_5m1ohdzyS0OmNkC7RPxo9bQ)(void* p, NI op);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_LIB_PRIVATE N_NIMCALL(tySequence_48htkG9cO2D6ATmPMpFeuow*, newSeq_Pkl0ZtaeGcwdqE9bx3MF7WA)(NI len);
static N_NIMCALL(void, Marker_tyRef_LtDmL6a1ws79cyGkTS4ZDOQ)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(tySequence_n1lfu84YYZHtqOit4XK9a2Q*, newSeq_kz6G9bjF9btQwTSFySH278SQ)(NI len);
static N_NIMCALL(void, Marker_tyRef_dw3xA32If3TX9abPvyj2LDQ)(void* p, NI op);
N_NOINLINE(void, raiseIndexError)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_BoxcolonObjectType__CcD6IYPdn4nlPMYfEQhewQ*, new_vJa1Px3VC82L38Sg03Basg)(void);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
N_LIB_PRIVATE N_NIMCALL(tyObject_BoxTargetcolonObjectType__RZuy9cwz9cfw8y9ab8un3pUpQ*, new_pGC2AQ3Hz7ppk6U7Vccb3w)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_ObstaclecolonObjectType__MfxUXOb9a5rFWMp79aQmNWqA*, new_DDohoHVU5SOictF39cS4TdA)(void);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tyRef_iHHre9ahzRDtyUNToF05Cog)(void* p, NI op);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src, TNimType* mt);
N_LIB_PRIVATE N_NIMCALL(NI, getIBoxAt_wDUHCBGLxjagOegAX9a7rUg)(tyObject_MapcolonObjectType__4y9b8sKN9bsYOudkhZrNpitg* map, tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ pos);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, eqeq__GMdYAiXVYFtXgUAy83DYgg)(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ x, tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ y);
N_LIB_PRIVATE N_NIMCALL(tyTuple_qmFwV9bFQ9a4cxfYwLzDR0lQ, getDestinStatus_WF9a9c5dQFWFvkcavet6jqLA)(tyObject_MapcolonObjectType__4y9b8sKN9bsYOudkhZrNpitg* map, tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ destin);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, colonanonymous__8llUUXRaS7N2Rhect6F0PQ)(NI value, NI size);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
N_LIB_PRIVATE N_NIMCALL(void, movePlayer_WrKDbUqmxbOGwa35F9cmt5A)(tyObject_MapcolonObjectType__4y9b8sKN9bsYOudkhZrNpitg* map, tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw direct);
N_LIB_PRIVATE N_NIMCALL(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ, X5BX5D__M8fLPtDcT9aAoQyfTfVp6TA)(tyObject_Table_nIG4O9c9a3gnDGm0H0nP9aqvA t, tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw key);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, checkBoxOnTarget_VkD5g6kI4QEUJEvBtCUYCg)(tyObject_MapcolonObjectType__4y9b8sKN9bsYOudkhZrNpitg* map);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getVisualMap_ZWzrfC0mDiQYvY6on1AgVQ)(tyObject_MapcolonObjectType__4y9b8sKN9bsYOudkhZrNpitg* map);
N_LIB_PRIVATE N_NIMCALL(tySequence_hmk4GiF9cJpv29aUeXPYPGfA*, newSeq_p5WxBPg9a9cR3Bb6aCSxRc6g)(NI len);
N_LIB_PRIVATE N_NIMCALL(tySequence_lBgZ7a89beZGYPl8PiANMTA*, newSeq_4cvYH6Zcve9c6YilXHgJ30Q)(NI len);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuRepeatChar)(NIM_CHAR c, NI count);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, join_nTMIi7o8Zy13sFPeiBsCQA)(NIM_CHAR* a, NI aLen_0, NimStringDesc* sep);
N_LIB_PRIVATE N_NIMCALL(tyEnum_InputAction_65PXn9bhXPOUlLz1qL3PCeQ, getInput_RfMgKTO9bx69b9bT3oeCLrvwA)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, readLine_fPRnXwDTqtynUYGl4OixAg)(FILE* f);
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size);
N_LIB_PRIVATE N_NIMCALL(void, updateGame_evOeUki6rXXwDbg8fHbh6g)(tyObject_MapcolonObjectType__4y9b8sKN9bsYOudkhZrNpitg* map, tyEnum_InputAction_65PXn9bhXPOUlLz1qL3PCeQ inputAction);
N_LIB_PRIVATE N_NIMCALL(void, draw_Ct5pKAbzYdOdwNwd5r5vTQ)(tyObject_MapcolonObjectType__4y9b8sKN9bsYOudkhZrNpitg* map);
N_LIB_PRIVATE N_NIMCALL(void, toTable_9aiFeC7cDng115aPs81eeFQ)(tyTuple_DTy5no9cl66GOLoMhrMJm8A* pairs, NI pairsLen_0, tyObject_Table_nIG4O9c9a3gnDGm0H0nP9aqvA* Result);
N_LIB_PRIVATE N_NIMCALL(void, initTable_N7bjLk6dihuKs0wAHJ9cAaQ)(NI initialSize, tyObject_Table_nIG4O9c9a3gnDGm0H0nP9aqvA* Result);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq__mGV0T7Bw850xV3ze03Q9cJw)(tyObject_Table_nIG4O9c9a3gnDGm0H0nP9aqvA* t, tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw key, tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ val);
static N_INLINE(NI, rawGet_AHdLKezz07NuzDUvZosDZgtables)(tyObject_Table_nIG4O9c9a3gnDGm0H0nP9aqvA t, tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw key, NI* hc);
static N_INLINE(NI, hash_wja033thh0Z4NAd9bdBGScwtables)(tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw x);
static N_INLINE(NIM_BOOL, isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables)(NI hcode);
static N_INLINE(NI, nextTry_OLPhxSyW9bte5CwHzzQVhfAtables)(NI h, NI maxHash);
static N_INLINE(NI, subInt)(NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(void, enlarge_aOo9ajIlXKCyMmB9ajxWw9a4g)(tyObject_Table_nIG4O9c9a3gnDGm0H0nP9aqvA* t);
N_LIB_PRIVATE N_NIMCALL(void, rawInsert_JIx5ModQQZZoBfiSfMt3gQ)(tyObject_Table_nIG4O9c9a3gnDGm0H0nP9aqvA* t, tySequence_y9aTBJ79cxanGa2fAuei6iIg** data, tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw key, tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ val, NI hc, NI h);
static N_INLINE(NI, rawGetKnownHC_n60yivyEBqJdPM2o7lYUhQtables)(tyObject_Table_nIG4O9c9a3gnDGm0H0nP9aqvA t, tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw key, NI hc);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted_nyaZAljVI03SH2d9cnD0WMw)(NimStringDesc** s, NI x);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TNimType NTI_yCEN9anxCD6mzBxGjuaRBdg_;
extern TNimType NTI_Gi06FkNeykJn7mrqRZYrkA_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
TNimType NTI_YKSlBm59bz8cnvLRFi6TueA_;
TNimType NTI_1v9bKyksXWMsm0vNwmZ4EuQ_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
TNimType NTI_pF0A5b9a9bWqyJfPW89cModmA_;
TNimType NTI_CcD6IYPdn4nlPMYfEQhewQ_;
TNimType NTI_5m1ohdzyS0OmNkC7RPxo9bQ_;
TNimType NTI_RZuy9cwz9cfw8y9ab8un3pUpQ_;
TNimType NTI_LtDmL6a1ws79cyGkTS4ZDOQ_;
TNimType NTI_MfxUXOb9a5rFWMp79aQmNWqA_;
TNimType NTI_dw3xA32If3TX9abPvyj2LDQ_;
TNimType NTI_4y9b8sKN9bsYOudkhZrNpitg_;
extern TNimType NTI_qP006YpEnVuz2e9aGF9cMpHw_;
extern TNimType NTI_48htkG9cO2D6ATmPMpFeuow_;
extern TNimType NTI_n1lfu84YYZHtqOit4XK9a2Q_;
TNimType NTI_iHHre9ahzRDtyUNToF05Cog_;
TNimType NTI_cLjoWhgzLRaR7YLGawE7Uw_;
extern TNimType NTI_hmk4GiF9cJpv29aUeXPYPGfA_;
STRING_LITERAL(TM_3idqVVpbLQLcl3rcp2D9asw_9, "Map is too small", 16);
NIM_CONST tyTuple_qmFwV9bFQ9a4cxfYwLzDR0lQ TM_3idqVVpbLQLcl3rcp2D9asw_19 = {((tyEnum_DestinStatus_uWnJ20JvX6gkNBB7pR6M6w) 1),
((NI) -1)}
;
STRING_LITERAL(TM_3idqVVpbLQLcl3rcp2D9asw_21, "len(a) == L seq modified while iterating over it", 48);
NIM_CONST tyTuple_qmFwV9bFQ9a4cxfYwLzDR0lQ TM_3idqVVpbLQLcl3rcp2D9asw_22 = {((tyEnum_DestinStatus_uWnJ20JvX6gkNBB7pR6M6w) 0),
((NI) -1)}
;
NIM_CONST struct {
  TGenericSeq Sup;
  tyTuple_Yt1nTvhqbfseJu4tLVyjRw data[16];
} TM_3idqVVpbLQLcl3rcp2D9asw_27 = {{16, 16}, {{((NI) 0),
((tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw) 0),
{((NI) 0),
((NI) 0)}
}
,
{((NI) 314159265),
((tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw) 0),
{((NI) 0),
((NI) -1)}
}
,
{((NI) 1),
((tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw) 1),
{((NI) 0),
((NI) 1)}
}
,
{((NI) 2),
((tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw) 2),
{((NI) -1),
((NI) 0)}
}
,
{((NI) 3),
((tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw) 3),
{((NI) 1),
((NI) 0)}
}
,
{((NI) 4),
((tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw) 4),
{((NI) 0),
((NI) 0)}
}
,
{((NI) 0),
((tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw) 0),
{((NI) 0),
((NI) 0)}
}
,
{((NI) 0),
((tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw) 0),
{((NI) 0),
((NI) 0)}
}
,
{((NI) 0),
((tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw) 0),
{((NI) 0),
((NI) 0)}
}
,
{((NI) 0),
((tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw) 0),
{((NI) 0),
((NI) 0)}
}
,
{((NI) 0),
((tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw) 0),
{((NI) 0),
((NI) 0)}
}
,
{((NI) 0),
((tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw) 0),
{((NI) 0),
((NI) 0)}
}
,
{((NI) 0),
((tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw) 0),
{((NI) 0),
((NI) 0)}
}
,
{((NI) 0),
((tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw) 0),
{((NI) 0),
((NI) 0)}
}
,
{((NI) 0),
((tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw) 0),
{((NI) 0),
((NI) 0)}
}
,
{((NI) 0),
((tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw) 0),
{((NI) 0),
((NI) 0)}
}
}};
NIM_CONST tyObject_Table_nIG4O9c9a3gnDGm0H0nP9aqvA TM_3idqVVpbLQLcl3rcp2D9asw_26 = {((tySequence_y9aTBJ79cxanGa2fAuei6iIg*)&TM_3idqVVpbLQLcl3rcp2D9asw_27), ((NI) 5)};
STRING_LITERAL(TM_3idqVVpbLQLcl3rcp2D9asw_35, "", 0);
STRING_LITERAL(TM_3idqVVpbLQLcl3rcp2D9asw_37, "\012", 1);
STRING_LITERAL(TM_3idqVVpbLQLcl3rcp2D9asw_38, "#", 1);
STRING_LITERAL(TM_3idqVVpbLQLcl3rcp2D9asw_39, "#\012", 2);
STRING_LITERAL(TM_3idqVVpbLQLcl3rcp2D9asw_41, "input is ", 9);
STRING_LITERAL(TM_3idqVVpbLQLcl3rcp2D9asw_42, "w", 1);
STRING_LITERAL(TM_3idqVVpbLQLcl3rcp2D9asw_43, "s", 1);
STRING_LITERAL(TM_3idqVVpbLQLcl3rcp2D9asw_44, "a", 1);
STRING_LITERAL(TM_3idqVVpbLQLcl3rcp2D9asw_45, "d", 1);
STRING_LITERAL(TM_3idqVVpbLQLcl3rcp2D9asw_46, "q", 1);

static N_INLINE(NI, modInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		if (!(b == ((NI) 0))) goto LA3_;
		raiseDivByZero();
	}
	LA3_: ;
	result = (NI)(a % b);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		if (!(b == ((NI) 0))) goto LA3_;
		raiseDivByZero();
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == ((NI) (IL64(-9223372036854775807) - IL64(1))));
		if (!(T7_)) goto LA8_;
		T7_ = (b == ((NI) -1));
		LA8_: ;
		if (!T7_) goto LA9_;
		raiseOverflow();
	}
	LA9_: ;
	result = (NI)(a / b);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ, nthCoord_YnKvJistBbyRII7Pq9ajnIA)(NI n, NI width, NI height) {
	tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ result;
	NI TM_3idqVVpbLQLcl3rcp2D9asw_2;
	NI TM_3idqVVpbLQLcl3rcp2D9asw_3;
	nimfr_("nthCoord", "push.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(48, "push.nim");
	TM_3idqVVpbLQLcl3rcp2D9asw_2 = modInt(n, width);
	result.Field0 = (NI)(TM_3idqVVpbLQLcl3rcp2D9asw_2);
	nimln_(49, "push.nim");
	TM_3idqVVpbLQLcl3rcp2D9asw_3 = divInt(n, width);
	result.Field1 = (NI)(TM_3idqVVpbLQLcl3rcp2D9asw_3);
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ, plus__V69cd9cWTLH4esNl9b6zfgteA)(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ pos0, tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ pos1) {
	tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ result;
	NI TM_3idqVVpbLQLcl3rcp2D9asw_4;
	NI TM_3idqVVpbLQLcl3rcp2D9asw_5;
	nimfr_("+", "push.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(53, "push.nim");
	TM_3idqVVpbLQLcl3rcp2D9asw_4 = addInt(pos0.Field0, pos1.Field0);
	result.Field0 = (NI)(TM_3idqVVpbLQLcl3rcp2D9asw_4);
	TM_3idqVVpbLQLcl3rcp2D9asw_5 = addInt(pos0.Field1, pos1.Field1);
	result.Field1 = (NI)(TM_3idqVVpbLQLcl3rcp2D9asw_5);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__mr9aVLAUz5GU2Vb6MCHzy5g)(tyObject_BoxcolonObjectType__CcD6IYPdn4nlPMYfEQhewQ* box) {
	NimStringDesc* result;
	nimfr_("$", "push.nim");
	result = (NimStringDesc*)0;
	nimln_(55, "push.nim");
	result = dollar__76rXyWcsgGy3rg1rEcHNNw((*box).pos);
	popFrame();
	return result;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(250, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(252, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(253, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim");
	nimln_(191, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(218, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(219, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim");
	nimln_(264, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(398, "system.nim");
		nimln_(264, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(265, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(398, "system.nim");
		nimln_(265, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(266, "gc.nim");
	(*dest) = src;
	popFrame();
}
static N_NIMCALL(void, Marker_tyRef_pF0A5b9a9bWqyJfPW89cModmA)(void* p, NI op) {
	tyObject_PlayercolonObjectType__YKSlBm59bz8cnvLRFi6TueA* a;
	a = (tyObject_PlayercolonObjectType__YKSlBm59bz8cnvLRFi6TueA*)p;
}
static N_NIMCALL(void, Marker_tyRef_5m1ohdzyS0OmNkC7RPxo9bQ)(void* p, NI op) {
	tyObject_BoxcolonObjectType__CcD6IYPdn4nlPMYfEQhewQ* a;
	a = (tyObject_BoxcolonObjectType__CcD6IYPdn4nlPMYfEQhewQ*)p;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}
static N_NIMCALL(void, Marker_tyRef_LtDmL6a1ws79cyGkTS4ZDOQ)(void* p, NI op) {
	tyObject_BoxTargetcolonObjectType__RZuy9cwz9cfw8y9ab8un3pUpQ* a;
	a = (tyObject_BoxTargetcolonObjectType__RZuy9cwz9cfw8y9ab8un3pUpQ*)p;
}
static N_NIMCALL(void, Marker_tyRef_dw3xA32If3TX9abPvyj2LDQ)(void* p, NI op) {
	tyObject_ObstaclecolonObjectType__MfxUXOb9a5rFWMp79aQmNWqA* a;
	a = (tyObject_ObstaclecolonObjectType__MfxUXOb9a5rFWMp79aQmNWqA*)p;
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim");
	nimln_(271, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(398, "system.nim");
		nimln_(271, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(272, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(273, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(274, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(398, "system.nim");
		nimln_(274, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(275, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(276, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(277, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(278, "gc.nim");
	(*dest) = src;
	popFrame();
}
static N_NIMCALL(void, Marker_tyRef_iHHre9ahzRDtyUNToF05Cog)(void* p, NI op) {
	tyObject_MapcolonObjectType__4y9b8sKN9bsYOudkhZrNpitg* a;
	a = (tyObject_MapcolonObjectType__4y9b8sKN9bsYOudkhZrNpitg*)p;
	nimGCvisit((void*)(*a).player, op);
	nimGCvisit((void*)(*a).boxes, op);
	nimGCvisit((void*)(*a).boxTargets, op);
	nimGCvisit((void*)(*a).obstacles, op);
}

N_LIB_PRIVATE N_NIMCALL(tyObject_MapcolonObjectType__4y9b8sKN9bsYOudkhZrNpitg*, newMap_vYQo9bUurZNloWZ8jelysMQ)(NI width, NI height, NI nBox, NI nObs) {
	tyObject_MapcolonObjectType__4y9b8sKN9bsYOudkhZrNpitg* result;
	tyObject_PlayercolonObjectType__YKSlBm59bz8cnvLRFi6TueA* player;
	tySequence_qP006YpEnVuz2e9aGF9cMpHw* boxes;
	tySequence_48htkG9cO2D6ATmPMpFeuow* boxTargets;
	tySequence_n1lfu84YYZHtqOit4XK9a2Q* obstacles;
	tyObject_MapcolonObjectType__4y9b8sKN9bsYOudkhZrNpitg* T12_;
	nimfr_("newMap", "push.nim");
	result = (tyObject_MapcolonObjectType__4y9b8sKN9bsYOudkhZrNpitg*)0;
	nimln_(58, "push.nim");
	{
		NI TM_3idqVVpbLQLcl3rcp2D9asw_6;
		NI TM_3idqVVpbLQLcl3rcp2D9asw_7;
		NI TM_3idqVVpbLQLcl3rcp2D9asw_8;
		tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA* e;
		NimStringDesc* T5_;
		TM_3idqVVpbLQLcl3rcp2D9asw_6 = mulInt(width, height);
		TM_3idqVVpbLQLcl3rcp2D9asw_7 = addInt(nBox, nObs);
		TM_3idqVVpbLQLcl3rcp2D9asw_8 = addInt((NI)(TM_3idqVVpbLQLcl3rcp2D9asw_7), ((NI) 1));
		if (!((NI)(TM_3idqVVpbLQLcl3rcp2D9asw_6) < (NI)(TM_3idqVVpbLQLcl3rcp2D9asw_8))) goto LA3_;
		e = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*)0;
		nimln_(2811, "system.nim");
		e = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*) newObj((&NTI_yCEN9anxCD6mzBxGjuaRBdg_), sizeof(tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA));
		(*e).Sup.Sup.m_type = (&NTI_Gi06FkNeykJn7mrqRZYrkA_);
		nimln_(59, "push.nim");
		T5_ = (NimStringDesc*)0;
		T5_ = (*e).Sup.message; (*e).Sup.message = copyStringRC1(((NimStringDesc*) &TM_3idqVVpbLQLcl3rcp2D9asw_9));
		if (T5_) nimGCunrefNoCycle(T5_);
		nimln_(2806, "system.nim");
		asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
		nimln_(59, "push.nim");
		raiseException((Exception*)e, "ValueError");
	}
	LA3_: ;
	nimln_(61, "push.nim");
	player = new_Z9bPY53FJdVBzfJKSz2bGgA();
	nimln_(62, "push.nim");
	boxes = newSeq_pkhiL4PxQF9bHsBsNmjE4zA(((NI)chckRange(nBox, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln_(63, "push.nim");
	boxTargets = newSeq_Pkl0ZtaeGcwdqE9bx3MF7WA(((NI)chckRange(nBox, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln_(64, "push.nim");
	obstacles = newSeq_kz6G9bjF9btQwTSFySH278SQ(((NI)chckRange(nObs, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln_(65, "push.nim");
	(*player).pos = nthCoord_YnKvJistBbyRII7Pq9ajnIA(((NI) 0), width, height);
	{
		NI iBox;
		NI i;
		iBox = (NI)0;
		nimln_(3519, "system.nim");
		i = ((NI) 0);
		{
			nimln_(3520, "system.nim");
			while (1) {
				NI TM_3idqVVpbLQLcl3rcp2D9asw_11;
				NI TM_3idqVVpbLQLcl3rcp2D9asw_12;
				NI TM_3idqVVpbLQLcl3rcp2D9asw_13;
				if (!(i < nBox)) goto LA8;
				nimln_(3521, "system.nim");
				iBox = i;
				if ((NU)(iBox) >= (NU)(boxes->Sup.len)) raiseIndexError();
				nimln_(67, "push.nim");
				asgnRefNoCycle((void**) (&boxes->data[iBox]), new_vJa1Px3VC82L38Sg03Basg());
				if ((NU)(iBox) >= (NU)(boxTargets->Sup.len)) raiseIndexError();
				nimln_(68, "push.nim");
				asgnRefNoCycle((void**) (&boxTargets->data[iBox]), new_pGC2AQ3Hz7ppk6U7Vccb3w());
				if ((NU)(iBox) >= (NU)(boxes->Sup.len)) raiseIndexError();
				nimln_(69, "push.nim");
				TM_3idqVVpbLQLcl3rcp2D9asw_11 = addInt(iBox, ((NI) 1));
				(*boxes->data[iBox]).pos = nthCoord_YnKvJistBbyRII7Pq9ajnIA((NI)(TM_3idqVVpbLQLcl3rcp2D9asw_11), width, height);
				if ((NU)(iBox) >= (NU)(boxTargets->Sup.len)) raiseIndexError();
				nimln_(70, "push.nim");
				TM_3idqVVpbLQLcl3rcp2D9asw_12 = addInt(iBox, ((NI) 1));
				(*boxTargets->data[iBox]).pos = nthCoord_YnKvJistBbyRII7Pq9ajnIA((NI)(TM_3idqVVpbLQLcl3rcp2D9asw_12), width, height);
				nimln_(3522, "system.nim");
				TM_3idqVVpbLQLcl3rcp2D9asw_13 = addInt(i, ((NI) 1));
				i = (NI)(TM_3idqVVpbLQLcl3rcp2D9asw_13);
			} LA8: ;
		}
	}
	{
		NI iObs;
		NI i_2;
		iObs = (NI)0;
		nimln_(3519, "system.nim");
		i_2 = ((NI) 0);
		{
			nimln_(3520, "system.nim");
			while (1) {
				NI TM_3idqVVpbLQLcl3rcp2D9asw_14;
				NI TM_3idqVVpbLQLcl3rcp2D9asw_15;
				NI TM_3idqVVpbLQLcl3rcp2D9asw_16;
				if (!(i_2 < nObs)) goto LA11;
				nimln_(3521, "system.nim");
				iObs = i_2;
				if ((NU)(iObs) >= (NU)(obstacles->Sup.len)) raiseIndexError();
				nimln_(72, "push.nim");
				asgnRefNoCycle((void**) (&obstacles->data[iObs]), new_DDohoHVU5SOictF39cS4TdA());
				if ((NU)(iObs) >= (NU)(obstacles->Sup.len)) raiseIndexError();
				nimln_(73, "push.nim");
				TM_3idqVVpbLQLcl3rcp2D9asw_14 = addInt(iObs, nObs);
				TM_3idqVVpbLQLcl3rcp2D9asw_15 = addInt((NI)(TM_3idqVVpbLQLcl3rcp2D9asw_14), ((NI) 2));
				(*obstacles->data[iObs]).pos = nthCoord_YnKvJistBbyRII7Pq9ajnIA((NI)(TM_3idqVVpbLQLcl3rcp2D9asw_15), width, height);
				nimln_(3522, "system.nim");
				TM_3idqVVpbLQLcl3rcp2D9asw_16 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_3idqVVpbLQLcl3rcp2D9asw_16);
			} LA11: ;
		}
	}
	nimln_(74, "push.nim");
	T12_ = (tyObject_MapcolonObjectType__4y9b8sKN9bsYOudkhZrNpitg*)0;
	T12_ = (tyObject_MapcolonObjectType__4y9b8sKN9bsYOudkhZrNpitg*) newObj((&NTI_iHHre9ahzRDtyUNToF05Cog_), sizeof(tyObject_MapcolonObjectType__4y9b8sKN9bsYOudkhZrNpitg));
	(*T12_).width = width;
	(*T12_).height = height;
	asgnRefNoCycle((void**) (&(*T12_).player), player);
	(*T12_).nBox = nBox;
	genericSeqAssign((&(*T12_).boxes), boxes, (&NTI_qP006YpEnVuz2e9aGF9cMpHw_));
	genericSeqAssign((&(*T12_).boxTargets), boxTargets, (&NTI_48htkG9cO2D6ATmPMpFeuow_));
	genericSeqAssign((&(*T12_).obstacles), obstacles, (&NTI_n1lfu84YYZHtqOit4XK9a2Q_));
	result = T12_;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, getIBoxAt_wDUHCBGLxjagOegAX9a7rUg)(tyObject_MapcolonObjectType__4y9b8sKN9bsYOudkhZrNpitg* map, tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ pos) {
	NI result;
	nimfr_("getIBoxAt", "push.nim");
{	result = (NI)0;
	{
		NI iBox;
		tyObject_BoxcolonObjectType__CcD6IYPdn4nlPMYfEQhewQ* box;
		tySequence_qP006YpEnVuz2e9aGF9cMpHw* colontmp_;
		NI i;
		iBox = (NI)0;
		box = (tyObject_BoxcolonObjectType__CcD6IYPdn4nlPMYfEQhewQ*)0;
		colontmp_ = (tySequence_qP006YpEnVuz2e9aGF9cMpHw*)0;
		nimln_(86, "push.nim");
		colontmp_ = (*map).boxes;
		nimln_(2285, "system.nim");
		i = ((NI) 0);
		{
			nimln_(2286, "system.nim");
			while (1) {
				NI T4_;
				NI TM_3idqVVpbLQLcl3rcp2D9asw_18;
				T4_ = (colontmp_ ? colontmp_->Sup.len : 0);
				if (!(i < T4_)) goto LA3;
				nimln_(2287, "system.nim");
				iBox = i;
				if ((NU)(i) >= (NU)(colontmp_->Sup.len)) raiseIndexError();
				box = colontmp_->data[i];
				nimln_(87, "push.nim");
				{
					NIM_BOOL T7_;
					T7_ = (NIM_BOOL)0;
					T7_ = eqeq__GMdYAiXVYFtXgUAy83DYgg((*box).pos, pos);
					if (!T7_) goto LA8_;
					nimln_(88, "push.nim");
					result = iBox;
					goto BeforeRet_;
				}
				LA8_: ;
				nimln_(2288, "system.nim");
				TM_3idqVVpbLQLcl3rcp2D9asw_18 = addInt(i, ((NI) 1));
				i = (NI)(TM_3idqVVpbLQLcl3rcp2D9asw_18);
			} LA3: ;
		}
	}
	nimln_(89, "push.nim");
	result = ((NI) -1);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, colonanonymous__8llUUXRaS7N2Rhect6F0PQ)(NI value, NI size) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	nimfr_(":anonymous", "push.nim");
	result = (NIM_BOOL)0;
	nimln_(96, "push.nim");
	T1_ = (NIM_BOOL)0;
	T1_ = (((NI) 0) <= value);
	if (!(T1_)) goto LA2_;
	T1_ = (value < size);
	LA2_: ;
	result = T1_;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyTuple_qmFwV9bFQ9a4cxfYwLzDR0lQ, getDestinStatus_WF9a9c5dQFWFvkcavet6jqLA)(tyObject_MapcolonObjectType__4y9b8sKN9bsYOudkhZrNpitg* map, tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ destin) {
	tyTuple_qmFwV9bFQ9a4cxfYwLzDR0lQ result;
	tyProc_RqErSzKvAG3vZYqc85mVBA cw;
	NI iBox;
	nimfr_("getDestinStatus", "push.nim");
{	memset((void*)(&result), 0, sizeof(result));
	nimln_(96, "push.nim");
	cw = colonanonymous__8llUUXRaS7N2Rhect6F0PQ;
	nimln_(97, "push.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = cw(destin.Field0, (*map).width);
		if (!(T3_)) goto LA4_;
		T3_ = cw(destin.Field1, (*map).height);
		LA4_: ;
		if (!!(T3_)) goto LA5_;
		nimln_(98, "push.nim");
		result = TM_3idqVVpbLQLcl3rcp2D9asw_19;
		goto BeforeRet_;
	}
	LA5_: ;
	{
		tyObject_ObstaclecolonObjectType__MfxUXOb9a5rFWMp79aQmNWqA* obstacle;
		tySequence_n1lfu84YYZHtqOit4XK9a2Q* colontmp_;
		NI i;
		NI L;
		NI T8_;
		obstacle = (tyObject_ObstaclecolonObjectType__MfxUXOb9a5rFWMp79aQmNWqA*)0;
		colontmp_ = (tySequence_n1lfu84YYZHtqOit4XK9a2Q*)0;
		nimln_(101, "push.nim");
		colontmp_ = (*map).obstacles;
		nimln_(3805, "system.nim");
		i = ((NI) 0);
		nimln_(3806, "system.nim");
		T8_ = (colontmp_ ? colontmp_->Sup.len : 0);
		L = T8_;
		{
			nimln_(3807, "system.nim");
			while (1) {
				NI TM_3idqVVpbLQLcl3rcp2D9asw_20;
				if (!(i < L)) goto LA10;
				nimln_(3808, "system.nim");
				if ((NU)(i) >= (NU)(colontmp_->Sup.len)) raiseIndexError();
				obstacle = colontmp_->data[i];
				nimln_(102, "push.nim");
				{
					NIM_BOOL T13_;
					T13_ = (NIM_BOOL)0;
					T13_ = eqeq__GMdYAiXVYFtXgUAy83DYgg((*obstacle).pos, destin);
					if (!T13_) goto LA14_;
					nimln_(103, "push.nim");
					result = TM_3idqVVpbLQLcl3rcp2D9asw_19;
					goto BeforeRet_;
				}
				LA14_: ;
				nimln_(3809, "system.nim");
				TM_3idqVVpbLQLcl3rcp2D9asw_20 = addInt(i, ((NI) 1));
				i = (NI)(TM_3idqVVpbLQLcl3rcp2D9asw_20);
				nimln_(3810, "system.nim");
				{
					NI T18_;
					T18_ = (colontmp_ ? colontmp_->Sup.len : 0);
					if (!!((T18_ == L))) goto LA19_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_3idqVVpbLQLcl3rcp2D9asw_21));
				}
				LA19_: ;
			} LA10: ;
		}
	}
	nimln_(106, "push.nim");
	iBox = getIBoxAt_wDUHCBGLxjagOegAX9a7rUg(map, destin);
	nimln_(107, "push.nim");
	{
		if (!(iBox == ((NI) -1))) goto LA23_;
		nimln_(108, "push.nim");
		result = TM_3idqVVpbLQLcl3rcp2D9asw_22;
		goto BeforeRet_;
	}
	LA23_: ;
	nimln_(109, "push.nim");
	result.Field0 = ((tyEnum_DestinStatus_uWnJ20JvX6gkNBB7pR6M6w) 2);
	result.Field1 = iBox;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, movePlayer_WrKDbUqmxbOGwa35F9cmt5A)(tyObject_MapcolonObjectType__4y9b8sKN9bsYOudkhZrNpitg* map, tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw direct) {
	tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ destin;
	tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ T1_;
	tyTuple_qmFwV9bFQ9a4cxfYwLzDR0lQ destinStatus;
	nimfr_("movePlayer", "push.nim");
	nimln_(113, "push.nim");
	nimln_(318, "tables.nim");
	T1_ = X5BX5D__M8fLPtDcT9aAoQyfTfVp6TA(TM_3idqVVpbLQLcl3rcp2D9asw_26, direct);
	destin = plus__V69cd9cWTLH4esNl9b6zfgteA((*(*map).player).pos, T1_);
	nimln_(114, "push.nim");
	destinStatus = getDestinStatus_WF9a9c5dQFWFvkcavet6jqLA(map, destin);
	nimln_(115, "push.nim");
	switch (destinStatus.Field0) {
	case ((tyEnum_DestinStatus_uWnJ20JvX6gkNBB7pR6M6w) 0):
	{
		nimln_(117, "push.nim");
		(*(*map).player).pos = destin;
	}
	break;
	case ((tyEnum_DestinStatus_uWnJ20JvX6gkNBB7pR6M6w) 1):
	{
	}
	break;
	case ((tyEnum_DestinStatus_uWnJ20JvX6gkNBB7pR6M6w) 2):
	{
		tyObject_BoxcolonObjectType__CcD6IYPdn4nlPMYfEQhewQ* box;
		tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ boxDestin;
		tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ T5_;
		tyTuple_qmFwV9bFQ9a4cxfYwLzDR0lQ boxDestinStatus;
		nimln_(121, "push.nim");
		if ((NU)(destinStatus.Field1) >= (NU)((*map).boxes->Sup.len)) raiseIndexError();
		box = (*map).boxes->data[destinStatus.Field1];
		nimln_(122, "push.nim");
		nimln_(318, "tables.nim");
		T5_ = X5BX5D__M8fLPtDcT9aAoQyfTfVp6TA(TM_3idqVVpbLQLcl3rcp2D9asw_26, direct);
		boxDestin = plus__V69cd9cWTLH4esNl9b6zfgteA((*box).pos, T5_);
		nimln_(123, "push.nim");
		boxDestinStatus = getDestinStatus_WF9a9c5dQFWFvkcavet6jqLA(map, boxDestin);
		nimln_(124, "push.nim");
		switch (boxDestinStatus.Field0) {
		case ((tyEnum_DestinStatus_uWnJ20JvX6gkNBB7pR6M6w) 0):
		{
			nimln_(126, "push.nim");
			(*(*map).player).pos = destin;
			nimln_(127, "push.nim");
			(*box).pos = boxDestin;
		}
		break;
		case ((tyEnum_DestinStatus_uWnJ20JvX6gkNBB7pR6M6w) 1):
		case ((tyEnum_DestinStatus_uWnJ20JvX6gkNBB7pR6M6w) 2):
		{
		}
		break;
		}
	}
	break;
	}
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, checkBoxOnTarget_VkD5g6kI4QEUJEvBtCUYCg)(tyObject_MapcolonObjectType__4y9b8sKN9bsYOudkhZrNpitg* map) {
	NIM_BOOL result;
	nimfr_("checkBoxOnTarget", "push.nim");
{	result = (NIM_BOOL)0;
	{
		tyObject_BoxTargetcolonObjectType__RZuy9cwz9cfw8y9ab8un3pUpQ* boxTarget;
		tySequence_48htkG9cO2D6ATmPMpFeuow* colontmp_;
		NI i;
		NI L;
		NI T2_;
		boxTarget = (tyObject_BoxTargetcolonObjectType__RZuy9cwz9cfw8y9ab8un3pUpQ*)0;
		colontmp_ = (tySequence_48htkG9cO2D6ATmPMpFeuow*)0;
		nimln_(132, "push.nim");
		colontmp_ = (*map).boxTargets;
		nimln_(3805, "system.nim");
		i = ((NI) 0);
		nimln_(3806, "system.nim");
		T2_ = (colontmp_ ? colontmp_->Sup.len : 0);
		L = T2_;
		{
			nimln_(3807, "system.nim");
			while (1) {
				NI TM_3idqVVpbLQLcl3rcp2D9asw_28;
				if (!(i < L)) goto LA4;
				nimln_(3808, "system.nim");
				if ((NU)(i) >= (NU)(colontmp_->Sup.len)) raiseIndexError();
				boxTarget = colontmp_->data[i];
				nimln_(133, "push.nim");
				{
					NI T7_;
					T7_ = (NI)0;
					T7_ = getIBoxAt_wDUHCBGLxjagOegAX9a7rUg(map, (*boxTarget).pos);
					if (!!((((NI) 0) <= T7_))) goto LA8_;
					nimln_(134, "push.nim");
					result = NIM_FALSE;
					goto BeforeRet_;
				}
				LA8_: ;
				nimln_(3809, "system.nim");
				TM_3idqVVpbLQLcl3rcp2D9asw_28 = addInt(i, ((NI) 1));
				i = (NI)(TM_3idqVVpbLQLcl3rcp2D9asw_28);
				nimln_(3810, "system.nim");
				{
					NI T12_;
					T12_ = (colontmp_ ? colontmp_->Sup.len : 0);
					if (!!((T12_ == L))) goto LA13_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_3idqVVpbLQLcl3rcp2D9asw_21));
				}
				LA13_: ;
			} LA4: ;
		}
	}
	nimln_(135, "push.nim");
	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getVisualMap_ZWzrfC0mDiQYvY6on1AgVQ)(tyObject_MapcolonObjectType__4y9b8sKN9bsYOudkhZrNpitg* map) {
	NimStringDesc* result;
	tySequence_hmk4GiF9cJpv29aUeXPYPGfA* visualMap;
	tySequence_hmk4GiF9cJpv29aUeXPYPGfA* result_2;
	NI pX;
	NI pY;
	NimStringDesc* hBorder;
	NI TM_3idqVVpbLQLcl3rcp2D9asw_36;
	NimStringDesc* T43_;
	nimfr_("getVisualMap", "push.nim");
	result = (NimStringDesc*)0;
	nimln_(140, "push.nim");
	nimln_(702, "sequtils.nim");
	result_2 = newSeq_p5WxBPg9a9cR3Bb6aCSxRc6g(((NI)chckRange((*map).height, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	{
		NI i;
		NI colontmp_;
		NI i_2;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(140, "push.nim");
		colontmp_ = (*map).height;
		nimln_(3519, "system.nim");
		i_2 = ((NI) 0);
		{
			nimln_(3520, "system.nim");
			while (1) {
				NI TM_3idqVVpbLQLcl3rcp2D9asw_29;
				if (!(i_2 < colontmp_)) goto LA3;
				nimln_(3521, "system.nim");
				i = i_2;
				if ((NU)(i) >= (NU)(result_2->Sup.len)) raiseIndexError();
				nimln_(140, "push.nim");
				asgnRefNoCycle((void**) (&result_2->data[i]), newSeq_4cvYH6Zcve9c6YilXHgJ30Q(((NI)chckRange((*map).width, ((NI) 0), ((NI) IL64(9223372036854775807))))));
				nimln_(3522, "system.nim");
				TM_3idqVVpbLQLcl3rcp2D9asw_29 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_3idqVVpbLQLcl3rcp2D9asw_29);
			} LA3: ;
		}
	}
	genericSeqAssign((&visualMap), result_2, (&NTI_hmk4GiF9cJpv29aUeXPYPGfA_));
	{
		NI iX;
		NI colontmp__2;
		NI i_3;
		iX = (NI)0;
		colontmp__2 = (NI)0;
		nimln_(141, "push.nim");
		colontmp__2 = (*map).width;
		nimln_(3519, "system.nim");
		i_3 = ((NI) 0);
		{
			nimln_(3520, "system.nim");
			while (1) {
				NI TM_3idqVVpbLQLcl3rcp2D9asw_31;
				if (!(i_3 < colontmp__2)) goto LA6;
				nimln_(3521, "system.nim");
				iX = i_3;
				{
					NI iY;
					NI colontmp__3;
					NI i_4;
					iY = (NI)0;
					colontmp__3 = (NI)0;
					nimln_(142, "push.nim");
					colontmp__3 = (*map).height;
					nimln_(3519, "system.nim");
					i_4 = ((NI) 0);
					{
						nimln_(3520, "system.nim");
						while (1) {
							NI TM_3idqVVpbLQLcl3rcp2D9asw_30;
							if (!(i_4 < colontmp__3)) goto LA9;
							nimln_(3521, "system.nim");
							iY = i_4;
							if ((NU)(iY) >= (NU)(visualMap->Sup.len)) raiseIndexError();
							if ((NU)(iX) >= (NU)(visualMap->data[iY]->Sup.len)) raiseIndexError();
							nimln_(143, "push.nim");
							visualMap->data[iY]->data[iX] = 32;
							nimln_(3522, "system.nim");
							TM_3idqVVpbLQLcl3rcp2D9asw_30 = addInt(i_4, ((NI) 1));
							i_4 = (NI)(TM_3idqVVpbLQLcl3rcp2D9asw_30);
						} LA9: ;
					}
				}
				TM_3idqVVpbLQLcl3rcp2D9asw_31 = addInt(i_3, ((NI) 1));
				i_3 = (NI)(TM_3idqVVpbLQLcl3rcp2D9asw_31);
			} LA6: ;
		}
	}
	{
		tyObject_BoxTargetcolonObjectType__RZuy9cwz9cfw8y9ab8un3pUpQ* boxTarget;
		tySequence_48htkG9cO2D6ATmPMpFeuow* colontmp__4;
		NI i_5;
		NI L;
		NI T11_;
		boxTarget = (tyObject_BoxTargetcolonObjectType__RZuy9cwz9cfw8y9ab8un3pUpQ*)0;
		colontmp__4 = (tySequence_48htkG9cO2D6ATmPMpFeuow*)0;
		nimln_(146, "push.nim");
		colontmp__4 = (*map).boxTargets;
		nimln_(3805, "system.nim");
		i_5 = ((NI) 0);
		nimln_(3806, "system.nim");
		T11_ = (colontmp__4 ? colontmp__4->Sup.len : 0);
		L = T11_;
		{
			nimln_(3807, "system.nim");
			while (1) {
				NI TM_3idqVVpbLQLcl3rcp2D9asw_32;
				if (!(i_5 < L)) goto LA13;
				nimln_(3808, "system.nim");
				if ((NU)(i_5) >= (NU)(colontmp__4->Sup.len)) raiseIndexError();
				boxTarget = colontmp__4->data[i_5];
				if ((NU)((*boxTarget).pos.Field1) >= (NU)(visualMap->Sup.len)) raiseIndexError();
				if ((NU)((*boxTarget).pos.Field0) >= (NU)(visualMap->data[(*boxTarget).pos.Field1]->Sup.len)) raiseIndexError();
				nimln_(147, "push.nim");
				visualMap->data[(*boxTarget).pos.Field1]->data[(*boxTarget).pos.Field0] = 46;
				nimln_(3809, "system.nim");
				TM_3idqVVpbLQLcl3rcp2D9asw_32 = addInt(i_5, ((NI) 1));
				i_5 = (NI)(TM_3idqVVpbLQLcl3rcp2D9asw_32);
				nimln_(3810, "system.nim");
				{
					NI T16_;
					T16_ = (colontmp__4 ? colontmp__4->Sup.len : 0);
					if (!!((T16_ == L))) goto LA17_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_3idqVVpbLQLcl3rcp2D9asw_21));
				}
				LA17_: ;
			} LA13: ;
		}
	}
	{
		tyObject_ObstaclecolonObjectType__MfxUXOb9a5rFWMp79aQmNWqA* obstacle;
		tySequence_n1lfu84YYZHtqOit4XK9a2Q* colontmp__5;
		NI i_6;
		NI L_2;
		NI T20_;
		obstacle = (tyObject_ObstaclecolonObjectType__MfxUXOb9a5rFWMp79aQmNWqA*)0;
		colontmp__5 = (tySequence_n1lfu84YYZHtqOit4XK9a2Q*)0;
		nimln_(149, "push.nim");
		colontmp__5 = (*map).obstacles;
		nimln_(3805, "system.nim");
		i_6 = ((NI) 0);
		nimln_(3806, "system.nim");
		T20_ = (colontmp__5 ? colontmp__5->Sup.len : 0);
		L_2 = T20_;
		{
			nimln_(3807, "system.nim");
			while (1) {
				NI TM_3idqVVpbLQLcl3rcp2D9asw_33;
				if (!(i_6 < L_2)) goto LA22;
				nimln_(3808, "system.nim");
				if ((NU)(i_6) >= (NU)(colontmp__5->Sup.len)) raiseIndexError();
				obstacle = colontmp__5->data[i_6];
				if ((NU)((*obstacle).pos.Field1) >= (NU)(visualMap->Sup.len)) raiseIndexError();
				if ((NU)((*obstacle).pos.Field0) >= (NU)(visualMap->data[(*obstacle).pos.Field1]->Sup.len)) raiseIndexError();
				nimln_(150, "push.nim");
				visualMap->data[(*obstacle).pos.Field1]->data[(*obstacle).pos.Field0] = 35;
				nimln_(3809, "system.nim");
				TM_3idqVVpbLQLcl3rcp2D9asw_33 = addInt(i_6, ((NI) 1));
				i_6 = (NI)(TM_3idqVVpbLQLcl3rcp2D9asw_33);
				nimln_(3810, "system.nim");
				{
					NI T25_;
					T25_ = (colontmp__5 ? colontmp__5->Sup.len : 0);
					if (!!((T25_ == L_2))) goto LA26_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_3idqVVpbLQLcl3rcp2D9asw_21));
				}
				LA26_: ;
			} LA22: ;
		}
	}
	nimln_(153, "push.nim");
	pX = (*(*map).player).pos.Field0;
	pY = (*(*map).player).pos.Field1;
	nimln_(154, "push.nim");
	if ((NU)(pY) >= (NU)(visualMap->Sup.len)) raiseIndexError();
	if ((NU)(pX) >= (NU)(visualMap->data[pY]->Sup.len)) raiseIndexError();
	switch (((NU8)(visualMap->data[pY]->data[pX]))) {
	case 32:
	case 111:
	{
		if ((NU)(pY) >= (NU)(visualMap->Sup.len)) raiseIndexError();
		if ((NU)(pX) >= (NU)(visualMap->data[pY]->Sup.len)) raiseIndexError();
		nimln_(156, "push.nim");
		visualMap->data[pY]->data[pX] = 80;
	}
	break;
	case 46:
	{
		if ((NU)(pY) >= (NU)(visualMap->Sup.len)) raiseIndexError();
		if ((NU)(pX) >= (NU)(visualMap->data[pY]->Sup.len)) raiseIndexError();
		nimln_(158, "push.nim");
		visualMap->data[pY]->data[pX] = 82;
	}
	break;
	default:
	{
	}
	break;
	}
	{
		tyObject_BoxcolonObjectType__CcD6IYPdn4nlPMYfEQhewQ* box;
		tySequence_qP006YpEnVuz2e9aGF9cMpHw* colontmp__6;
		NI i_7;
		NI L_3;
		NI T32_;
		box = (tyObject_BoxcolonObjectType__CcD6IYPdn4nlPMYfEQhewQ*)0;
		colontmp__6 = (tySequence_qP006YpEnVuz2e9aGF9cMpHw*)0;
		nimln_(162, "push.nim");
		colontmp__6 = (*map).boxes;
		nimln_(3805, "system.nim");
		i_7 = ((NI) 0);
		nimln_(3806, "system.nim");
		T32_ = (colontmp__6 ? colontmp__6->Sup.len : 0);
		L_3 = T32_;
		{
			nimln_(3807, "system.nim");
			while (1) {
				NI bX;
				NI bY;
				NI TM_3idqVVpbLQLcl3rcp2D9asw_34;
				if (!(i_7 < L_3)) goto LA34;
				nimln_(3808, "system.nim");
				if ((NU)(i_7) >= (NU)(colontmp__6->Sup.len)) raiseIndexError();
				box = colontmp__6->data[i_7];
				nimln_(163, "push.nim");
				bX = (*box).pos.Field0;
				bY = (*box).pos.Field1;
				nimln_(164, "push.nim");
				if ((NU)(bY) >= (NU)(visualMap->Sup.len)) raiseIndexError();
				if ((NU)(bX) >= (NU)(visualMap->data[bY]->Sup.len)) raiseIndexError();
				switch (((NU8)(visualMap->data[bY]->data[bX]))) {
				case 32:
				case 111:
				case 112:
				{
					if ((NU)(bY) >= (NU)(visualMap->Sup.len)) raiseIndexError();
					if ((NU)(bX) >= (NU)(visualMap->data[bY]->Sup.len)) raiseIndexError();
					nimln_(166, "push.nim");
					visualMap->data[bY]->data[bX] = 111;
				}
				break;
				case 46:
				{
					if ((NU)(bY) >= (NU)(visualMap->Sup.len)) raiseIndexError();
					if ((NU)(bX) >= (NU)(visualMap->data[bY]->Sup.len)) raiseIndexError();
					nimln_(168, "push.nim");
					visualMap->data[bY]->data[bX] = 64;
				}
				break;
				default:
				{
				}
				break;
				}
				nimln_(3809, "system.nim");
				TM_3idqVVpbLQLcl3rcp2D9asw_34 = addInt(i_7, ((NI) 1));
				i_7 = (NI)(TM_3idqVVpbLQLcl3rcp2D9asw_34);
				nimln_(3810, "system.nim");
				{
					NI T40_;
					T40_ = (colontmp__6 ? colontmp__6->Sup.len : 0);
					if (!!((T40_ == L_3))) goto LA41_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_3idqVVpbLQLcl3rcp2D9asw_21));
				}
				LA41_: ;
			} LA34: ;
		}
	}
	nimln_(173, "push.nim");
	result = copyString(((NimStringDesc*) &TM_3idqVVpbLQLcl3rcp2D9asw_35));
	nimln_(174, "push.nim");
	TM_3idqVVpbLQLcl3rcp2D9asw_36 = addInt((*map).width, ((NI) 2));
	hBorder = nsuRepeatChar(35, ((NI)chckRange((NI)(TM_3idqVVpbLQLcl3rcp2D9asw_36), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln_(176, "push.nim");
	T43_ = (NimStringDesc*)0;
	T43_ = rawNewString(hBorder->Sup.len + 1);
appendString(T43_, hBorder);
appendString(T43_, ((NimStringDesc*) &TM_3idqVVpbLQLcl3rcp2D9asw_37));
	result = resizeString(result, T43_->Sup.len + 0);
appendString(result, T43_);
	{
		NI iY_2;
		NI colontmp__7;
		NI i_8;
		iY_2 = (NI)0;
		colontmp__7 = (NI)0;
		nimln_(177, "push.nim");
		colontmp__7 = (*map).height;
		nimln_(3519, "system.nim");
		i_8 = ((NI) 0);
		{
			nimln_(3520, "system.nim");
			while (1) {
				NimStringDesc* T47_;
				NimStringDesc* T48_;
				NI TM_3idqVVpbLQLcl3rcp2D9asw_40;
				if (!(i_8 < colontmp__7)) goto LA46;
				nimln_(3521, "system.nim");
				iY_2 = i_8;
				nimln_(178, "push.nim");
				T47_ = (NimStringDesc*)0;
				if ((NU)(iY_2) >= (NU)(visualMap->Sup.len)) raiseIndexError();
				T48_ = (NimStringDesc*)0;
				T48_ = join_nTMIi7o8Zy13sFPeiBsCQA(visualMap->data[iY_2]->data, visualMap->data[iY_2]->Sup.len, ((NimStringDesc*) &TM_3idqVVpbLQLcl3rcp2D9asw_35));
				T47_ = rawNewString(T48_->Sup.len + 3);
appendString(T47_, ((NimStringDesc*) &TM_3idqVVpbLQLcl3rcp2D9asw_38));
appendString(T47_, T48_);
appendString(T47_, ((NimStringDesc*) &TM_3idqVVpbLQLcl3rcp2D9asw_39));
				result = resizeString(result, T47_->Sup.len + 0);
appendString(result, T47_);
				nimln_(3522, "system.nim");
				TM_3idqVVpbLQLcl3rcp2D9asw_40 = addInt(i_8, ((NI) 1));
				i_8 = (NI)(TM_3idqVVpbLQLcl3rcp2D9asw_40);
			} LA46: ;
		}
	}
	nimln_(179, "push.nim");
	result = resizeString(result, hBorder->Sup.len + 0);
appendString(result, hBorder);
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = memcmp(a, b, ((size_t) (size)));
	result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL T11_;
{	result = (NIM_BOOL)0;
	{
		if (!(a == b)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == NIM_NIL);
		if (T7_) goto LA8_;
		T7_ = (b == NIM_NIL);
		LA8_: ;
		if (!T7_) goto LA9_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA9_: ;
	T11_ = (NIM_BOOL)0;
	T11_ = ((*a).Sup.len == (*b).Sup.len);
	if (!(T11_)) goto LA12_;
	T11_ = equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem(((void*) ((*a).data)), ((void*) ((*b).data)), ((NI) ((*a).Sup.len)));
	LA12_: ;
	result = T11_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyEnum_InputAction_65PXn9bhXPOUlLz1qL3PCeQ, getInput_RfMgKTO9bx69b9bT3oeCLrvwA)(void) {
	tyEnum_InputAction_65PXn9bhXPOUlLz1qL3PCeQ result;
	NimStringDesc* input;
	tyArray_Re75IspeoxXy2oCZHwcRrA T1_;
	nimfr_("getInput", "push.nim");
	result = (tyEnum_InputAction_65PXn9bhXPOUlLz1qL3PCeQ)0;
	nimln_(182, "push.nim");
	input = readLine_fPRnXwDTqtynUYGl4OixAg(stdin);
	nimln_(183, "push.nim");
	memset((void*)T1_, 0, sizeof(T1_));
	T1_[0] = copyString(((NimStringDesc*) &TM_3idqVVpbLQLcl3rcp2D9asw_41));
	T1_[1] = copyString(input);
	echoBinSafe(T1_, 2);
	nimln_(184, "push.nim");
	if (eqStrings(input, ((NimStringDesc*) &TM_3idqVVpbLQLcl3rcp2D9asw_42))) goto LA2_;
	if (eqStrings(input, ((NimStringDesc*) &TM_3idqVVpbLQLcl3rcp2D9asw_43))) goto LA3_;
	if (eqStrings(input, ((NimStringDesc*) &TM_3idqVVpbLQLcl3rcp2D9asw_44))) goto LA4_;
	if (eqStrings(input, ((NimStringDesc*) &TM_3idqVVpbLQLcl3rcp2D9asw_45))) goto LA5_;
	if (eqStrings(input, ((NimStringDesc*) &TM_3idqVVpbLQLcl3rcp2D9asw_46))) goto LA6_;
	goto LA7_;
	LA2_: ;
	{
		nimln_(186, "push.nim");
		result = ((tyEnum_InputAction_65PXn9bhXPOUlLz1qL3PCeQ) 0);
	}
	goto LA8_;
	LA3_: ;
	{
		nimln_(188, "push.nim");
		result = ((tyEnum_InputAction_65PXn9bhXPOUlLz1qL3PCeQ) 1);
	}
	goto LA8_;
	LA4_: ;
	{
		nimln_(190, "push.nim");
		result = ((tyEnum_InputAction_65PXn9bhXPOUlLz1qL3PCeQ) 2);
	}
	goto LA8_;
	LA5_: ;
	{
		nimln_(192, "push.nim");
		result = ((tyEnum_InputAction_65PXn9bhXPOUlLz1qL3PCeQ) 3);
	}
	goto LA8_;
	LA6_: ;
	{
		nimln_(194, "push.nim");
		result = ((tyEnum_InputAction_65PXn9bhXPOUlLz1qL3PCeQ) 4);
	}
	goto LA8_;
	LA7_: ;
	{
		nimln_(196, "push.nim");
		result = ((tyEnum_InputAction_65PXn9bhXPOUlLz1qL3PCeQ) 5);
	}
	LA8_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, updateGame_evOeUki6rXXwDbg8fHbh6g)(tyObject_MapcolonObjectType__4y9b8sKN9bsYOudkhZrNpitg* map, tyEnum_InputAction_65PXn9bhXPOUlLz1qL3PCeQ inputAction) {
	nimfr_("updateGame", "push.nim");
	nimln_(200, "push.nim");
	switch (inputAction) {
	case ((tyEnum_InputAction_65PXn9bhXPOUlLz1qL3PCeQ) 0):
	{
		nimln_(202, "push.nim");
		movePlayer_WrKDbUqmxbOGwa35F9cmt5A(map, ((tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw) 0));
	}
	break;
	case ((tyEnum_InputAction_65PXn9bhXPOUlLz1qL3PCeQ) 1):
	{
		nimln_(204, "push.nim");
		movePlayer_WrKDbUqmxbOGwa35F9cmt5A(map, ((tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw) 1));
	}
	break;
	case ((tyEnum_InputAction_65PXn9bhXPOUlLz1qL3PCeQ) 2):
	{
		nimln_(206, "push.nim");
		movePlayer_WrKDbUqmxbOGwa35F9cmt5A(map, ((tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw) 2));
	}
	break;
	case ((tyEnum_InputAction_65PXn9bhXPOUlLz1qL3PCeQ) 3):
	{
		nimln_(208, "push.nim");
		movePlayer_WrKDbUqmxbOGwa35F9cmt5A(map, ((tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw) 3));
	}
	break;
	case ((tyEnum_InputAction_65PXn9bhXPOUlLz1qL3PCeQ) 4):
	{
		nimln_(1500, "system.nim");
		exit(((NI) 0));
	}
	break;
	case ((tyEnum_InputAction_65PXn9bhXPOUlLz1qL3PCeQ) 5):
	{
	}
	break;
	}
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, draw_Ct5pKAbzYdOdwNwd5r5vTQ)(tyObject_MapcolonObjectType__4y9b8sKN9bsYOudkhZrNpitg* map) {
	tyArray_nHXaesL0DJZHyVS07ARPRA T1_;
	nimfr_("draw", "push.nim");
	nimln_(215, "push.nim");
	memset((void*)T1_, 0, sizeof(T1_));
	T1_[0] = getVisualMap_ZWzrfC0mDiQYvY6on1AgVQ(map);
	echoBinSafe(T1_, 1);
	popFrame();
}

static N_INLINE(NI, hash_wja033thh0Z4NAd9bdBGScwtables)(tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw x) {
	NI result;
	nimfr_("hash", "hashes.nim");
	result = (NI)0;
	nimln_(129, "hashes.nim");
	result = x;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables)(NI hcode) {
	NIM_BOOL result;
	nimfr_("isFilled", "tableimpl.nim");
	result = (NIM_BOOL)0;
	nimln_(18, "tableimpl.nim");
	nimln_(398, "system.nim");
	nimln_(18, "tableimpl.nim");
	result = !((hcode == ((NI) 0)));
	popFrame();
	return result;
}

static N_INLINE(NI, nextTry_OLPhxSyW9bte5CwHzzQVhfAtables)(NI h, NI maxHash) {
	NI result;
	NI TM_3idqVVpbLQLcl3rcp2D9asw_47;
	nimfr_("nextTry", "tableimpl.nim");
	result = (NI)0;
	nimln_(28, "tableimpl.nim");
	TM_3idqVVpbLQLcl3rcp2D9asw_47 = addInt(h, ((NI) 1));
	result = (NI)((NI)(TM_3idqVVpbLQLcl3rcp2D9asw_47) & maxHash);
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, rawGet_AHdLKezz07NuzDUvZosDZgtables)(tyObject_Table_nIG4O9c9a3gnDGm0H0nP9aqvA t, tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw key, NI* hc) {
	NI result;
	NI h;
	NI T5_;
	NI TM_3idqVVpbLQLcl3rcp2D9asw_48;
	nimfr_("rawGet", "tableimpl.nim");
{	result = (NI)0;
	nimln_(53, "tableimpl.nim");
	(*hc) = hash_wja033thh0Z4NAd9bdBGScwtables(key);
	{
		if (!((*hc) == ((NI) 0))) goto LA3_;
		nimln_(45, "tableimpl.nim");
		(*hc) = ((NI) 314159265);
	}
	LA3_: ;
	nimln_(31, "tableimpl.nim");
	nimln_(116, "tables.nim");
	T5_ = (t.data ? (t.data->Sup.len-1) : -1);
	h = (NI)((*hc) & T5_);
	{
		nimln_(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL T8_;
			NI T15_;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			T8_ = (NIM_BOOL)0;
			T8_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(t.data->data[h].Field0);
			if (!T8_) goto LA7;
			nimln_(37, "tableimpl.nim");
			{
				NIM_BOOL T11_;
				T11_ = (NIM_BOOL)0;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T11_ = (t.data->data[h].Field0 == (*hc));
				if (!(T11_)) goto LA12_;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T11_ = (t.data->data[h].Field1 == key);
				LA12_: ;
				if (!T11_) goto LA13_;
				nimln_(38, "tableimpl.nim");
				result = h;
				goto BeforeRet_;
			}
			LA13_: ;
			nimln_(39, "tableimpl.nim");
			nimln_(116, "tables.nim");
			T15_ = (t.data ? (t.data->Sup.len-1) : -1);
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, T15_);
		} LA7: ;
	}
	nimln_(40, "tableimpl.nim");
	TM_3idqVVpbLQLcl3rcp2D9asw_48 = subInt(((NI) -1), h);
	result = (NI)(TM_3idqVVpbLQLcl3rcp2D9asw_48);
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, rawGetKnownHC_n60yivyEBqJdPM2o7lYUhQtables)(tyObject_Table_nIG4O9c9a3gnDGm0H0nP9aqvA t, tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw key, NI hc) {
	NI result;
	NI h;
	NI T1_;
	NI TM_3idqVVpbLQLcl3rcp2D9asw_49;
	nimfr_("rawGetKnownHC", "tableimpl.nim");
{	result = (NI)0;
	nimln_(31, "tableimpl.nim");
	nimln_(116, "tables.nim");
	T1_ = (t.data ? (t.data->Sup.len-1) : -1);
	h = (NI)(hc & T1_);
	{
		nimln_(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL T4_;
			NI T11_;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			T4_ = (NIM_BOOL)0;
			T4_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(t.data->data[h].Field0);
			if (!T4_) goto LA3;
			nimln_(37, "tableimpl.nim");
			{
				NIM_BOOL T7_;
				T7_ = (NIM_BOOL)0;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T7_ = (t.data->data[h].Field0 == hc);
				if (!(T7_)) goto LA8_;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T7_ = (t.data->data[h].Field1 == key);
				LA8_: ;
				if (!T7_) goto LA9_;
				nimln_(38, "tableimpl.nim");
				result = h;
				goto BeforeRet_;
			}
			LA9_: ;
			nimln_(39, "tableimpl.nim");
			nimln_(116, "tables.nim");
			T11_ = (t.data ? (t.data->Sup.len-1) : -1);
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, T11_);
		} LA3: ;
	}
	nimln_(40, "tableimpl.nim");
	TM_3idqVVpbLQLcl3rcp2D9asw_49 = subInt(((NI) -1), h);
	result = (NI)(TM_3idqVVpbLQLcl3rcp2D9asw_49);
	}BeforeRet_: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, unknown_pushInit000)(void) {
	nimfr_("push", "push.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, unknown_pushDatInit000)(void) {
static TNimNode* TM_3idqVVpbLQLcl3rcp2D9asw_10[2];
static TNimNode* TM_3idqVVpbLQLcl3rcp2D9asw_17[7];
static TNimNode* TM_3idqVVpbLQLcl3rcp2D9asw_23[5];
NI TM_3idqVVpbLQLcl3rcp2D9asw_25;
static char* NIM_CONST TM_3idqVVpbLQLcl3rcp2D9asw_24[5] = {
"up", 
"down", 
"left", 
"right", 
"immobile"};
static TNimNode TM_3idqVVpbLQLcl3rcp2D9asw_0[21];
NTI_YKSlBm59bz8cnvLRFi6TueA_.size = sizeof(tyObject_PlayercolonObjectType__YKSlBm59bz8cnvLRFi6TueA);
NTI_YKSlBm59bz8cnvLRFi6TueA_.kind = 18;
NTI_YKSlBm59bz8cnvLRFi6TueA_.base = 0;
NTI_YKSlBm59bz8cnvLRFi6TueA_.flags = 3;
NTI_1v9bKyksXWMsm0vNwmZ4EuQ_.size = sizeof(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ);
NTI_1v9bKyksXWMsm0vNwmZ4EuQ_.kind = 18;
NTI_1v9bKyksXWMsm0vNwmZ4EuQ_.base = 0;
NTI_1v9bKyksXWMsm0vNwmZ4EuQ_.flags = 3;
TM_3idqVVpbLQLcl3rcp2D9asw_10[0] = &TM_3idqVVpbLQLcl3rcp2D9asw_0[2];
TM_3idqVVpbLQLcl3rcp2D9asw_0[2].kind = 1;
TM_3idqVVpbLQLcl3rcp2D9asw_0[2].offset = offsetof(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ, Field0);
TM_3idqVVpbLQLcl3rcp2D9asw_0[2].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_3idqVVpbLQLcl3rcp2D9asw_0[2].name = "Field0";
TM_3idqVVpbLQLcl3rcp2D9asw_10[1] = &TM_3idqVVpbLQLcl3rcp2D9asw_0[3];
TM_3idqVVpbLQLcl3rcp2D9asw_0[3].kind = 1;
TM_3idqVVpbLQLcl3rcp2D9asw_0[3].offset = offsetof(tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ, Field1);
TM_3idqVVpbLQLcl3rcp2D9asw_0[3].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_3idqVVpbLQLcl3rcp2D9asw_0[3].name = "Field1";
TM_3idqVVpbLQLcl3rcp2D9asw_0[1].len = 2; TM_3idqVVpbLQLcl3rcp2D9asw_0[1].kind = 2; TM_3idqVVpbLQLcl3rcp2D9asw_0[1].sons = &TM_3idqVVpbLQLcl3rcp2D9asw_10[0];
NTI_1v9bKyksXWMsm0vNwmZ4EuQ_.node = &TM_3idqVVpbLQLcl3rcp2D9asw_0[1];
TM_3idqVVpbLQLcl3rcp2D9asw_0[0].kind = 1;
TM_3idqVVpbLQLcl3rcp2D9asw_0[0].offset = offsetof(tyObject_PlayercolonObjectType__YKSlBm59bz8cnvLRFi6TueA, pos);
TM_3idqVVpbLQLcl3rcp2D9asw_0[0].typ = (&NTI_1v9bKyksXWMsm0vNwmZ4EuQ_);
TM_3idqVVpbLQLcl3rcp2D9asw_0[0].name = "pos";
NTI_YKSlBm59bz8cnvLRFi6TueA_.node = &TM_3idqVVpbLQLcl3rcp2D9asw_0[0];
NTI_pF0A5b9a9bWqyJfPW89cModmA_.size = sizeof(tyObject_PlayercolonObjectType__YKSlBm59bz8cnvLRFi6TueA*);
NTI_pF0A5b9a9bWqyJfPW89cModmA_.kind = 22;
NTI_pF0A5b9a9bWqyJfPW89cModmA_.base = (&NTI_YKSlBm59bz8cnvLRFi6TueA_);
NTI_pF0A5b9a9bWqyJfPW89cModmA_.flags = 2;
NTI_pF0A5b9a9bWqyJfPW89cModmA_.marker = Marker_tyRef_pF0A5b9a9bWqyJfPW89cModmA;
NTI_CcD6IYPdn4nlPMYfEQhewQ_.size = sizeof(tyObject_BoxcolonObjectType__CcD6IYPdn4nlPMYfEQhewQ);
NTI_CcD6IYPdn4nlPMYfEQhewQ_.kind = 18;
NTI_CcD6IYPdn4nlPMYfEQhewQ_.base = 0;
NTI_CcD6IYPdn4nlPMYfEQhewQ_.flags = 3;
TM_3idqVVpbLQLcl3rcp2D9asw_0[4].kind = 1;
TM_3idqVVpbLQLcl3rcp2D9asw_0[4].offset = offsetof(tyObject_BoxcolonObjectType__CcD6IYPdn4nlPMYfEQhewQ, pos);
TM_3idqVVpbLQLcl3rcp2D9asw_0[4].typ = (&NTI_1v9bKyksXWMsm0vNwmZ4EuQ_);
TM_3idqVVpbLQLcl3rcp2D9asw_0[4].name = "pos";
NTI_CcD6IYPdn4nlPMYfEQhewQ_.node = &TM_3idqVVpbLQLcl3rcp2D9asw_0[4];
NTI_5m1ohdzyS0OmNkC7RPxo9bQ_.size = sizeof(tyObject_BoxcolonObjectType__CcD6IYPdn4nlPMYfEQhewQ*);
NTI_5m1ohdzyS0OmNkC7RPxo9bQ_.kind = 22;
NTI_5m1ohdzyS0OmNkC7RPxo9bQ_.base = (&NTI_CcD6IYPdn4nlPMYfEQhewQ_);
NTI_5m1ohdzyS0OmNkC7RPxo9bQ_.flags = 2;
NTI_5m1ohdzyS0OmNkC7RPxo9bQ_.marker = Marker_tyRef_5m1ohdzyS0OmNkC7RPxo9bQ;
NTI_RZuy9cwz9cfw8y9ab8un3pUpQ_.size = sizeof(tyObject_BoxTargetcolonObjectType__RZuy9cwz9cfw8y9ab8un3pUpQ);
NTI_RZuy9cwz9cfw8y9ab8un3pUpQ_.kind = 18;
NTI_RZuy9cwz9cfw8y9ab8un3pUpQ_.base = 0;
NTI_RZuy9cwz9cfw8y9ab8un3pUpQ_.flags = 3;
TM_3idqVVpbLQLcl3rcp2D9asw_0[5].kind = 1;
TM_3idqVVpbLQLcl3rcp2D9asw_0[5].offset = offsetof(tyObject_BoxTargetcolonObjectType__RZuy9cwz9cfw8y9ab8un3pUpQ, pos);
TM_3idqVVpbLQLcl3rcp2D9asw_0[5].typ = (&NTI_1v9bKyksXWMsm0vNwmZ4EuQ_);
TM_3idqVVpbLQLcl3rcp2D9asw_0[5].name = "pos";
NTI_RZuy9cwz9cfw8y9ab8un3pUpQ_.node = &TM_3idqVVpbLQLcl3rcp2D9asw_0[5];
NTI_LtDmL6a1ws79cyGkTS4ZDOQ_.size = sizeof(tyObject_BoxTargetcolonObjectType__RZuy9cwz9cfw8y9ab8un3pUpQ*);
NTI_LtDmL6a1ws79cyGkTS4ZDOQ_.kind = 22;
NTI_LtDmL6a1ws79cyGkTS4ZDOQ_.base = (&NTI_RZuy9cwz9cfw8y9ab8un3pUpQ_);
NTI_LtDmL6a1ws79cyGkTS4ZDOQ_.flags = 2;
NTI_LtDmL6a1ws79cyGkTS4ZDOQ_.marker = Marker_tyRef_LtDmL6a1ws79cyGkTS4ZDOQ;
NTI_MfxUXOb9a5rFWMp79aQmNWqA_.size = sizeof(tyObject_ObstaclecolonObjectType__MfxUXOb9a5rFWMp79aQmNWqA);
NTI_MfxUXOb9a5rFWMp79aQmNWqA_.kind = 18;
NTI_MfxUXOb9a5rFWMp79aQmNWqA_.base = 0;
NTI_MfxUXOb9a5rFWMp79aQmNWqA_.flags = 3;
TM_3idqVVpbLQLcl3rcp2D9asw_0[6].kind = 1;
TM_3idqVVpbLQLcl3rcp2D9asw_0[6].offset = offsetof(tyObject_ObstaclecolonObjectType__MfxUXOb9a5rFWMp79aQmNWqA, pos);
TM_3idqVVpbLQLcl3rcp2D9asw_0[6].typ = (&NTI_1v9bKyksXWMsm0vNwmZ4EuQ_);
TM_3idqVVpbLQLcl3rcp2D9asw_0[6].name = "pos";
NTI_MfxUXOb9a5rFWMp79aQmNWqA_.node = &TM_3idqVVpbLQLcl3rcp2D9asw_0[6];
NTI_dw3xA32If3TX9abPvyj2LDQ_.size = sizeof(tyObject_ObstaclecolonObjectType__MfxUXOb9a5rFWMp79aQmNWqA*);
NTI_dw3xA32If3TX9abPvyj2LDQ_.kind = 22;
NTI_dw3xA32If3TX9abPvyj2LDQ_.base = (&NTI_MfxUXOb9a5rFWMp79aQmNWqA_);
NTI_dw3xA32If3TX9abPvyj2LDQ_.flags = 2;
NTI_dw3xA32If3TX9abPvyj2LDQ_.marker = Marker_tyRef_dw3xA32If3TX9abPvyj2LDQ;
NTI_4y9b8sKN9bsYOudkhZrNpitg_.size = sizeof(tyObject_MapcolonObjectType__4y9b8sKN9bsYOudkhZrNpitg);
NTI_4y9b8sKN9bsYOudkhZrNpitg_.kind = 18;
NTI_4y9b8sKN9bsYOudkhZrNpitg_.base = 0;
NTI_4y9b8sKN9bsYOudkhZrNpitg_.flags = 2;
TM_3idqVVpbLQLcl3rcp2D9asw_17[0] = &TM_3idqVVpbLQLcl3rcp2D9asw_0[8];
TM_3idqVVpbLQLcl3rcp2D9asw_0[8].kind = 1;
TM_3idqVVpbLQLcl3rcp2D9asw_0[8].offset = offsetof(tyObject_MapcolonObjectType__4y9b8sKN9bsYOudkhZrNpitg, height);
TM_3idqVVpbLQLcl3rcp2D9asw_0[8].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_3idqVVpbLQLcl3rcp2D9asw_0[8].name = "height";
TM_3idqVVpbLQLcl3rcp2D9asw_17[1] = &TM_3idqVVpbLQLcl3rcp2D9asw_0[9];
TM_3idqVVpbLQLcl3rcp2D9asw_0[9].kind = 1;
TM_3idqVVpbLQLcl3rcp2D9asw_0[9].offset = offsetof(tyObject_MapcolonObjectType__4y9b8sKN9bsYOudkhZrNpitg, width);
TM_3idqVVpbLQLcl3rcp2D9asw_0[9].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_3idqVVpbLQLcl3rcp2D9asw_0[9].name = "width";
TM_3idqVVpbLQLcl3rcp2D9asw_17[2] = &TM_3idqVVpbLQLcl3rcp2D9asw_0[10];
TM_3idqVVpbLQLcl3rcp2D9asw_0[10].kind = 1;
TM_3idqVVpbLQLcl3rcp2D9asw_0[10].offset = offsetof(tyObject_MapcolonObjectType__4y9b8sKN9bsYOudkhZrNpitg, player);
TM_3idqVVpbLQLcl3rcp2D9asw_0[10].typ = (&NTI_pF0A5b9a9bWqyJfPW89cModmA_);
TM_3idqVVpbLQLcl3rcp2D9asw_0[10].name = "player";
TM_3idqVVpbLQLcl3rcp2D9asw_17[3] = &TM_3idqVVpbLQLcl3rcp2D9asw_0[11];
TM_3idqVVpbLQLcl3rcp2D9asw_0[11].kind = 1;
TM_3idqVVpbLQLcl3rcp2D9asw_0[11].offset = offsetof(tyObject_MapcolonObjectType__4y9b8sKN9bsYOudkhZrNpitg, nBox);
TM_3idqVVpbLQLcl3rcp2D9asw_0[11].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_3idqVVpbLQLcl3rcp2D9asw_0[11].name = "nBox";
TM_3idqVVpbLQLcl3rcp2D9asw_17[4] = &TM_3idqVVpbLQLcl3rcp2D9asw_0[12];
TM_3idqVVpbLQLcl3rcp2D9asw_0[12].kind = 1;
TM_3idqVVpbLQLcl3rcp2D9asw_0[12].offset = offsetof(tyObject_MapcolonObjectType__4y9b8sKN9bsYOudkhZrNpitg, boxes);
TM_3idqVVpbLQLcl3rcp2D9asw_0[12].typ = (&NTI_qP006YpEnVuz2e9aGF9cMpHw_);
TM_3idqVVpbLQLcl3rcp2D9asw_0[12].name = "boxes";
TM_3idqVVpbLQLcl3rcp2D9asw_17[5] = &TM_3idqVVpbLQLcl3rcp2D9asw_0[13];
TM_3idqVVpbLQLcl3rcp2D9asw_0[13].kind = 1;
TM_3idqVVpbLQLcl3rcp2D9asw_0[13].offset = offsetof(tyObject_MapcolonObjectType__4y9b8sKN9bsYOudkhZrNpitg, boxTargets);
TM_3idqVVpbLQLcl3rcp2D9asw_0[13].typ = (&NTI_48htkG9cO2D6ATmPMpFeuow_);
TM_3idqVVpbLQLcl3rcp2D9asw_0[13].name = "boxTargets";
TM_3idqVVpbLQLcl3rcp2D9asw_17[6] = &TM_3idqVVpbLQLcl3rcp2D9asw_0[14];
TM_3idqVVpbLQLcl3rcp2D9asw_0[14].kind = 1;
TM_3idqVVpbLQLcl3rcp2D9asw_0[14].offset = offsetof(tyObject_MapcolonObjectType__4y9b8sKN9bsYOudkhZrNpitg, obstacles);
TM_3idqVVpbLQLcl3rcp2D9asw_0[14].typ = (&NTI_n1lfu84YYZHtqOit4XK9a2Q_);
TM_3idqVVpbLQLcl3rcp2D9asw_0[14].name = "obstacles";
TM_3idqVVpbLQLcl3rcp2D9asw_0[7].len = 7; TM_3idqVVpbLQLcl3rcp2D9asw_0[7].kind = 2; TM_3idqVVpbLQLcl3rcp2D9asw_0[7].sons = &TM_3idqVVpbLQLcl3rcp2D9asw_17[0];
NTI_4y9b8sKN9bsYOudkhZrNpitg_.node = &TM_3idqVVpbLQLcl3rcp2D9asw_0[7];
NTI_iHHre9ahzRDtyUNToF05Cog_.size = sizeof(tyObject_MapcolonObjectType__4y9b8sKN9bsYOudkhZrNpitg*);
NTI_iHHre9ahzRDtyUNToF05Cog_.kind = 22;
NTI_iHHre9ahzRDtyUNToF05Cog_.base = (&NTI_4y9b8sKN9bsYOudkhZrNpitg_);
NTI_iHHre9ahzRDtyUNToF05Cog_.flags = 2;
NTI_iHHre9ahzRDtyUNToF05Cog_.marker = Marker_tyRef_iHHre9ahzRDtyUNToF05Cog;
NTI_cLjoWhgzLRaR7YLGawE7Uw_.size = sizeof(tyEnum_Direct_cLjoWhgzLRaR7YLGawE7Uw);
NTI_cLjoWhgzLRaR7YLGawE7Uw_.kind = 14;
NTI_cLjoWhgzLRaR7YLGawE7Uw_.base = 0;
NTI_cLjoWhgzLRaR7YLGawE7Uw_.flags = 3;
for (TM_3idqVVpbLQLcl3rcp2D9asw_25 = 0; TM_3idqVVpbLQLcl3rcp2D9asw_25 < 5; TM_3idqVVpbLQLcl3rcp2D9asw_25++) {
TM_3idqVVpbLQLcl3rcp2D9asw_0[TM_3idqVVpbLQLcl3rcp2D9asw_25+15].kind = 1;
TM_3idqVVpbLQLcl3rcp2D9asw_0[TM_3idqVVpbLQLcl3rcp2D9asw_25+15].offset = TM_3idqVVpbLQLcl3rcp2D9asw_25;
TM_3idqVVpbLQLcl3rcp2D9asw_0[TM_3idqVVpbLQLcl3rcp2D9asw_25+15].name = TM_3idqVVpbLQLcl3rcp2D9asw_24[TM_3idqVVpbLQLcl3rcp2D9asw_25];
TM_3idqVVpbLQLcl3rcp2D9asw_23[TM_3idqVVpbLQLcl3rcp2D9asw_25] = &TM_3idqVVpbLQLcl3rcp2D9asw_0[TM_3idqVVpbLQLcl3rcp2D9asw_25+15];
}
TM_3idqVVpbLQLcl3rcp2D9asw_0[20].len = 5; TM_3idqVVpbLQLcl3rcp2D9asw_0[20].kind = 2; TM_3idqVVpbLQLcl3rcp2D9asw_0[20].sons = &TM_3idqVVpbLQLcl3rcp2D9asw_23[0];
NTI_cLjoWhgzLRaR7YLGawE7Uw_.node = &TM_3idqVVpbLQLcl3rcp2D9asw_0[20];
}

